-- Italian translation by Impaler on CurseForge

FishingTranslations["itIT"] = {
	ABOUT_TAB = "Informazioni...", -- Needs review
	ADD = "Aggiungi", -- Needs review
	ADDFISHIEMSG = "%s aggiunto nel luogo %s", -- Needs review
	ADDSCHOOLMSG = "%s aggiunto nel luogo %s", -- Needs review
	ALLZOMGPETS = "Includi tutte le mascotte", -- Needs review
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "Vestiti e vai a pescare!", -- Needs review
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Cambia l'abbigliamento da pesca", -- Needs review
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Abilita/disabilita la finestra #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Abilita/disabilita il pannello dei luoghi #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Abilita/disabilita il pannello delle opzioni #NAME#", -- Needs review
	BOBBER_NAME = "Galleggiante", -- Needs review
	CAST = "lancia", -- Needs review
	CAUGHT_IN_ZONES = "Pescato in: %s", -- Needs review
	CAUGHTTHISMANY = "Pescato:", -- Needs review
	CAUGHTTHISTOTAL = "Totale:", -- Needs review
	CHECK = "controllo", -- Needs review
	CLEANUP = "pulizia", -- Needs review
	CLEANUP_DONEMSG = "Vecchie impostazioni rimosse per |c#RED#%s|r: %s.", -- Needs review
	CLEANUP_NONEMSG = "Non rimangono vecchie impostazioni", -- Needs review
	CLEANUP_NOOLDMSG = "Non ci sono vecchie impostazioni per il giocatore |c#GREEN#%s|r.", -- Needs review
	CLEANUP_WILLMSG = "Rimangono delle vecchie impostazioni per |c#RED#%s|r: %s.", -- Needs review
	CLICKTOSWITCH_INFO = "Se abilitato, un clic sinistro cambia abbigliamento, altrimenti apre la finestra di Fishing Buddy.", -- Needs review
	CLICKTOSWITCH_ONOFF = "Clicca per cambiare", -- Needs review
	COMPATIBLE_SWITCHER = "Non \195\168 stato trovato alcun cambio di abbigliamento compatibile", -- Needs review
	CONFIG_ALWAYSLURE_INFO = "Se abilitato, mette un'esca ogni volta che la canna non ne ha una.", -- Needs review
	CONFIG_ALWAYSLURE_ONOFF = "Metti sempre l'esca.", -- Needs review
	CONFIG_AUTOLOOT_INFO = "Se abilitato, la predazione automatica viene attivata pescando.", -- Needs review
	CONFIG_AUTOLOOT_ONOFF = "Predazione automatica", -- Needs review
	CONFIG_AUTOOPEN_INFO = "Se abilitato, usa il doppio clic per aprire oggetti di missione di pesca", -- Needs review
	CONFIG_AUTOOPEN_ONOFF = "Apri oggetti di missione", -- Needs review
	CONFIG_BGSOUNDS_INFO = "Se abilitato, i suoni saranno abilitati mentre WoW \195\168 in secondo piano.", -- Needs review
	CONFIG_BGSOUNDS_ONOFF = "Suoni in secondo piano", -- Needs review
	CONFIG_CONTESTS_INFO = "Mostra timer per le gare di pesca", -- Needs review
	CONFIG_CONTESTS_ONOFF = "Supporto per gara di pesca", -- Needs review
	CONFIG_DERBYTIMER_INFO = "Se abilitato, mostra un conto alla rovescia per la gara di pesca dei Kalu'ak e un conto alla rovescia del tempo rimasto.", -- Needs review
	CONFIG_DERBYTIMER_ONOFF = "Timer della gara di pesca dei Kalu'ak", -- Needs review
	CONFIG_DRINKHEAVILY_INFO = "Se abilitato, bevi #LAGER# ogni volta che stai pescando e hai sete.", -- Needs review
	CONFIG_DRINKHEAVILY_ONOFF = "Bevi Birra", -- Needs review
	CONFIG_EASYCAST_INFO = "Abilita il lancio con un doppio clic destro.", -- Needs review
	CONFIG_EASYCAST_ONOFF = "Lancio facile", -- Needs review
	CONFIG_EASYLURES_INFO = "Se abilitato, verr\195\160 applicata un'esca alla tua canna prima di cominciare a pescare, ogni volta che te ne serve una.", -- Needs review
	CONFIG_EASYLURES_ONOFF = "Esche Facili", -- Needs review
	CONFIG_ENHANCESOUNDS_INFO = "Quando abilitato, massimizza il volume dei suoni e minimizza il volume ambientale per sentire meglio il ruomore del galleggiante.", -- Needs review
	CONFIG_ENHANCESOUNDS_ONOFF = "Aumenta i suoni legati alla pesca.", -- Needs review
	CONFIG_FINDFISH_INFO = "Abilita l'abilit\195\160 \"Trova Pesci\" quando vestito da pescatore", -- Needs review
	CONFIG_FINDFISH_ONOFF = "Trova Pesci", -- Needs review
	CONFIG_FISHINGBUDDY_INFO = "Fai uscire il tuo amichetto speciale mentre peschi.", -- Needs review
	CONFIG_FISHINGBUDDY_ONOFF = "Fishing Buddy", -- Needs review
	CONFIG_FISHINGFLUFF_INFO = "Abilita tutto il divertimento possibile immaginabile mentre stai pescando.", -- Needs review
	CONFIG_FISHINGFLUFF_ONOFF = "Divertimento con la pesca", -- Needs review
	CONFIG_FISHWATCH_INFO = "Mostra un testo in sovrimpressione con i pesci pescati nella zona attuale", -- Needs review
	CONFIG_FISHWATCHONLY_INFO = "Mostra l'OsservaPesca solo quando si sta pescando", -- Needs review
	CONFIG_FISHWATCHONLY_ONOFF = "Solo mentre si pesca", -- Needs review
	CONFIG_FISHWATCH_ONOFF = "OsservaPesca", -- Needs review
	CONFIG_FISHWATCHPERCENT_INFO = "Mostra la percentuale per ogni tipo di pesce nel display dell'osservatore", -- Needs review
	CONFIG_FISHWATCHPERCENT_ONOFF = "Mostra percentuali", -- Needs review
	CONFIG_FISHWATCHSKILL_INFO = "Mostra l'attuale abilit\195\160 in Pesca e i mod nell'area dell'OsservaPesca", -- Needs review
	CONFIG_FISHWATCHSKILL_ONOFF = "Abilit\195\160 attuale", -- Needs review
	CONFIG_FISHWATCHTIME_INFO = "Mostra il tempo passato dall'ultima volta che hai equipaggiato una canna", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Mostra il tempo trascorso", -- Needs review
	CONFIG_FISHWATCHZONE_INFO = "Mostra la zona attuale nell'area dell'OsservaPesca", -- Needs review
	CONFIG_FISHWATCHZONE_ONOFF = "Zona attuale", -- Needs review
	CONFIG_LASTRESORT_INFO = "Se abilitato, aggiungi l'esca pi\195\185 grande in possesso anche se non fa arrivare al 100% di possibilit\195\160 di pescare", -- Needs review
	CONFIG_LASTRESORT_ONOFF = "Esca Ultima Possibilit\195\160", -- Needs review
	CONFIG_MAXSOUND_INFO = "Se abilitato, imposta il volume al massimo mentre si pesca.", -- Needs review
	CONFIG_MAXSOUND_ONOFF = "Volume massimo.", -- Needs review
	CONFIG_MINIMAPBUTTON_INFO = "Mostra un'icona #NAME# sulla minimappa", -- Needs review
	CONFIG_MINIMAPBUTTON_ONOFF = "Mostra l'icona sulal minimapppa", -- Needs review
	[" CONFIG_MINIMAPMOVE_INFO"] = "Se abilitato, l'icona della minimappa pu\195\178 essere spostata trascinandola", -- Needs review
	[" CONFIG_MINIMAPMOVE_ONOFF"] = "Trascinabile", -- Needs review
	CONFIG_MOUNTEDCAST_INFO = "Se abilitato, permette di lanciare a cavallo.", -- Needs review
	CONFIG_MOUNTEDCAST_ONOFF = "A cavallo.", -- Needs review
	CONFIG_ONLYMINE_INFO = "Se abilitato, Lancio Facile controller\195\160 solo la canna nel tuo abbigliamento (ad es. non cercher\195\160 tutte le possibili canne)", -- Needs review
	CONFIG_ONLYMINE_ONOFF = "Indossa solo la Canna", -- Needs review
	CONFIG_OUTFITTER_TEXT = "Bonus abilit\195\160 abbigliamento: %s#BR#Punteggio di stile di Draznar: %d", -- Needs review
	CONFIG_SHOWLOCATIONZONES_INFO = "Mostra sia la zona che la sottozona", -- Needs review
	CONFIG_SHOWLOCATIONZONES_ONOFF = "Mostra zone", -- Needs review
	CONFIG_SHOWNEWFISHIES_INFO = "Mostra un messaggio nell'area di chat quando viene pescato un nuovo pesce nella zona attuale", -- Needs review
	CONFIG_SHOWNEWFISHIES_ONOFF = "Mostra nuovi pesci", -- Needs review
	CONFIG_SHOWPOOLS_INFO = "Se abilitato, i luoghi delle pozze conosciuti saranno mostrati sulla minimappa.", -- Needs review
	CONFIG_SHOWPOOLS_ONOFF = "Mostra pozze", -- Needs review
	CONFIG_SORTBYPERCENT_INFO = "Ordina la visualizzazione per il numero di pesci pescati invece che per nome.", -- Needs review
	CONFIG_SORTBYPERCENT_ONOFF = "Ordina per numero pescati", -- Needs review
	CONFIG_SPARKLIES_INFO = "Se abilitato, il luccichio sulle pozze di pesca sar\195\160 pi\195\185 visibile pescando.", -- Needs review
	CONFIG_SPARKLIES_ONOFF = "Migliora le pozze", -- Needs review
	CONFIG_STVPOOLSONLY_INFO = "Se abilitato, Lancio Facile sar\195\160 attivo solo se il cursore \195\168 su una zona pescabile", -- Needs review
	CONFIG_STVPOOLSONLY_ONOFF = "Lancia solo nelle pozze", -- Needs review
	CONFIG_STVTIMER_INFO = "Se abilitato, mostra un conto alla rovescia per l'inizio della gara di pesca di Rovotorto, e un conto alla rovescia del tempo rimanente.", -- Needs review
	CONFIG_STVTIMER_ONOFF = "Timer della gara di pesca di Rovotorto", -- Needs review
	CONFIG_TOOLTIPS_INFO = "Se abilitato, le informazioni sul pesce pescato saranno visualizzate nei tooltip.", -- Needs review
	CONFIG_TOOLTIPS_ONOFF = "Mostra informazioni di pesca nei tooltip", -- Needs review
	CONFIG_TURNOFFPVP_INFO = "Se abilitato, il PVP sar\195\160 disattivato equipaggiando una canna da pesca.", -- Needs review
	CONFIG_TURNOFFPVP_ONOFF = "Disabilita PVP", -- Needs review
	CONFIG_TURNONSOUND_INFO = "Se abilitato, attiva sempre i suoni pescando.", -- Needs review
	CONFIG_TURNONSOUND_ONOFF = "Forza sonoro.", -- Needs review
	CONFIG_USEACTION_INFO = "Se abilitato, #NAME# cercher\195\160 per un pulsante nella barra azioni da usare per lanciare.", -- Needs review
	CONFIG_USEACTION_ONOFF = "Usa Azione", -- Needs review
	CONFIG_WATCHBOBBER_INFO = "Se abilitato, #NAME# non lancer\195\160 se il curse \195\168 sopra un galleggiante.", -- Needs review
	CONFIG_WATCHBOBBER_ONOFF = "Guarda il galleggiante", -- Needs review
	COPPER_COIN = "Moneta di rame", -- Needs review
	CURRENT = "corrente", -- Needs review
	CURRENT_HELP = "|c#GREEN#/fb #CURRENT# #RESET#|r#BRSPCS#Resetta i pesci pescati durante la sessione attuale..", -- Needs review
	DERBY = "Derby", -- Needs review
	DESCRIPTION1 = "Tieni traccia dei pesci pescati", -- Needs review
	DESCRIPTION2 = "e gestisci il tuo abbigliamento da pesca", -- Needs review
	ELAPSED = "Trascorso", -- Needs review
	ELDER_CLEARWATER = "L'Anziano Acquafresca urla: (%a)+ ha vinto la Gara di pesca dei Kalu'ak!", -- Needs review
	ELEM_WATER = "Elementale dell'Acqua", -- Needs review
	EXTRAVAGANZA = "Stravaganza", -- Needs review
	FAILEDINIT = "Non \195\168 stato inizializzato correttamente.", -- Needs review
	FATLADYSINGS = "|c#RED#%s\195\168 oltre|r (%d:%02d left)", -- Needs review
	FISH = "Pesce", -- Needs review
	FISHTYPES = "Tipi di pesce: %d", -- Needs review
	FLOATING_DEBRIS = "Detriti galleggianti", -- Needs review
	FLOATING_WRECKAGE = "Relitti galleggianti", -- Needs review
	FORCE = "forza", -- Needs review
	GOLD_COIN = "Moneta d'oro", -- Needs review
	HELP = "aiuto", -- Needs review
	HIDEINWATCHER = "Mostra questo pesce nell'OsservaPesce", -- Needs review
	HOURLY = "all'ora", -- Needs review
	KEYS_ALT_TEXT = "Alt", -- Needs review
	KEYS_CTRL_TEXT = "Control", -- Needs review
	KEYS_LABEL_TEXT = "Modificatori:", -- Needs review
	KEYS_NONE_TEXT = "Nessuno", -- Needs review
	KEYS_SHIFT_TEXT = "Shift", -- Needs review
	LAGER = "Birra del Capitano Rumsey", -- Needs review
	LEFTCLICKTODRAG = "Clic sinistro per trascinare", -- Needs review
	LOCATIONS_INFO = "Mostra dove hai catturato pesci sia per Area che per Tipo di Pesce", -- Needs review
	LOCATIONS_TAB = "Luoghi", -- Needs review
	MINIMAPBUTTONPLACEMENT = "Piazzamento", -- Needs review
	MINIMAPBUTTONPLACEMENTTOOLTIP = "Permette di muovere l'icona #NAME# attorno alla minimappa.", -- Needs review
	MINIMAPBUTTONRADIUS = "Distanza", -- Needs review
	MINIMAPBUTTONRADIUSTOOLTIP = "Determina quanto pu\195\178 essere distante dalla minimappa l'icona #NAME#.", -- Needs review
	MINIMUMSKILL = "Abilit\195\160 minima: %d", -- Needs review
	NAME = "Fishing Buddy", -- Needs review
	NODATAMSG = "Nessun dato di pesca disponibile.", -- Needs review
	NONEAVAILABLE_MSG = "Nessuno disponibile.", -- Needs review
	NOREALM = "reame sconosciuto", -- Needs review
	NOTLINKABLE = "<Non si pu\195\178 mostrare il collegamento dell'oggetto>", -- Needs review
	NOW = "adesso", -- Needs review
	OFFSET_LABEL_TEXT = "Offset:", -- Needs review
	OIL_SPILL = "Perdita di Petrolio", -- Needs review
	OPTIONS_INFO = "Imposta le opzioni #NAME#", -- Needs review
	OPTIONS_TAB = "Opzioni", -- Needs review
	OUTFITS = "Abbigliamenti", -- Needs review
	POINT = "punto", -- Needs review
	POINTS = "punti", -- Needs review
	POST_HELP = "Puoi assegnare sia l'impostazione della finestra che l'abbigliamento#BR#ai tasti desiderati nella finestra \"Assegnazione Tasti\".", -- Needs review
	PRE_HELP = "Puoi usare |c#GREEN#/fishingbuddy|r o |c#GREEN#/fb|r per tutti i comandi#BR#|c#GREEN#/fb|r: da solo, toglie la finestra di Fishing Buddy#BR#|c#GREEN#/fb #HELP#|r: mostra questo messaggio", -- Needs review
	RANDOM = "Casuale", -- Needs review
	RAW = "Grezzo", -- Needs review
	REPLACE = "rimpiazza", -- Needs review
	RESET = "resetta", -- Needs review
	RIGGLE_BASSBAIT = "Riggle Escastorta urla: Abbiamo un vincitore! (%a)+ \195\168 il Mastro Pescatore!", -- Needs review
	RIGHTCLICKFORMENU = "Clicca con il destro per il menu", -- Needs review
	ROLE_ADDON_AUTHORS = "Autori dell'Addon degni di nota", -- Needs review
	ROLE_HELP_BUGS = "Risoluzione Bug e aiuto per la programmazione", -- Needs review
	ROLE_HELP_SUGGESTIONS = "Suggerisci novit\195\160", -- Needs review
	ROLE_TRANSLATE_DEDE = "Traduzione tedesca", -- Needs review
	ROLE_TRANSLATE_ESES = "Traduzione spagnola", -- Needs review
	ROLE_TRANSLATE_FRFR = "Traduzione francese", -- Needs review
	ROLE_TRANSLATE_KOKR = "Traduzione coreana", -- Needs review
	ROLE_TRANSLATE_PTBR = "Traduzione portoghese/brasiliana", -- Needs review
	ROLE_TRANSLATE_RURU = "Traduzione russa", -- Needs review
	ROLE_TRANSLATE_ZHCN = "Traduzione in cinese semplificato", -- Needs review
	ROLE_TRANSLATE_ZHTW = "Traduzione in cinese tradizionale", -- Needs review
	SCHOOL = "Branco", -- Needs review
	SHOWFISHIES = "Mostra pesci", -- Needs review
	SHOWFISHIES_INFO = "Mostra la storia di pesca raggruppata per tipo di pesci", -- Needs review
	SHOWLOCATIONS = "Luoghi", -- Needs review
	SHOWLOCATIONS_INFO = "Mostra la storia della pesca raggruppata per aree di pesca", -- Needs review
	SILVER_COIN = "Moneta d'argento", -- Needs review
	STVZONENAME = "Valle di Rovotorto", -- Needs review
	SWITCH = "cambia", -- Needs review
	SWITCH_HELP = "|c#GREEN#/fb #SWITCH#|r#BRSPCS#cambia abbigliamento (se OutfitDisplayFrame o Outfitter sono disponibili)", -- Needs review
	THANKS = "Grazie a tutti!", -- Needs review
	TIMELEFT = "%s finisce in %d:%02d", -- Needs review
	TIMER = "timer", -- Needs review
	TIMERRESET_HELP = "|c#GREEN#/fb #TIMER# #RESET#|r#BRSPCS#Resetta la posizione del timer della Stravaganza spostandolo#BRSPCS#al centro dello schermo.", -- Needs review
	TIMETOGO = "%s inizia in %d:%02d", -- Needs review
	TOOLTIP_HINT = "Suggerimento:", -- Needs review
	TOOLTIP_HINTSWITCH = "clicca per cambiare abbigliamento", -- Needs review
	TOOLTIP_HINTTOGGLE = "clicca per mostrare la finestra #NAME#", -- Needs review
	TOOMANYFISHERMEN = "Hai pi\195\185 di un mod di Lancio Facile installato", -- Needs review
	TOTAL = "Totale", -- Needs review
	TOTALS = "Totali", -- Needs review
	UPDATE = "aggiorna", -- Needs review
	UPDATEDB = "aggiornaDB", -- Needs review
	UPDATEDB_HELP = "|c#GREEN#/fb #UPDATEDB# [#FORCE#]|r#BRSPCS#Prova a cercare i nomi di tutti i pesci sconosciuti..#BRSPCS#Un tentativo viene fatto per saltare i pesci 'rari' che potrebbero disconnetterti#BRSPCS#dal server -- usa l'opzione '#FORCE#' per evitare il controllo.", -- Needs review
	UPDATEDB_MSG = "Aggiornato %d nomi di pesci.", -- Needs review
	WATCHER = "osservatore", -- Needs review
	WATCHER_HELP = "|c#GREEN#/fb #WATCHER#|r [|c#GREEN##WATCHER_LOCK#|r o |c#GREEN##WATCHER_UNLOCK#|r o |c#GREEN##RESET#|r]#BRSPCS#Sblocca l'osservatore per muovere la finestra,#BRSPCS#blocca per fermarla, reset per resettarla.", -- Needs review
	WATCHER_LOCK = "blocca", -- Needs review
	WATCHER_TAB = "Osservatore", -- Needs review
	WATCHER_UNLOCK = "sblocca", -- Needs review
	WEEKLY = "settimanale", -- Needs review
}

