-- Brazilian Portuguese, nomadbr on CurseForge

FishingTranslations["ptBR"] = {
	-- ABOUT_TAB = "About",
	ADD = "adicionar", -- Needs review
	ADDFISHIEMSG = "Adicionado %s para a localiza\195\167\195\163o %s.", -- Needs review
	ADDSCHOOLMSG = "Adicionado '%s' para a localiza\195\167\195\163o %s.", -- Needs review
	-- ALLZOMGPETS = "Include all pets",
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "Vista-se e v\195\161 pescar", -- Needs review
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Mudar equipamento de pesca", -- Needs review
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Alternar a Janela  #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Alternar o Painel de Localiza\195\167\195\163o #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Alternar o Painel de Op\195\167\195\181es #NAME#", -- Needs review
	BOBBER_NAME = "Isca de Pesca", -- Needs review
	CAST = "lan\195\167ar", -- Needs review
	CAUGHT_IN_ZONES = "Capturados em: %s", -- Needs review
	CAUGHTTHISMANY = "Capturados:", -- Needs review
	CAUGHTTHISTOTAL = "Total:", -- Needs review
	CHECK = "verificar", -- Needs review
	CLEANUP = "limpeza", -- Needs review
	CLEANUP_DONEMSG = "Configura\195\167\195\181es antigas removidas para |c#RED#%s|r: %s.", -- Needs review
	CLEANUP_NONEMSG = "Nenhuma configura\195\167\195\163o antiga permanece.", -- Needs review
	CLEANUP_NOOLDMSG = "N\195\163o h\195\161 configura\195\167\195\181es antigas para o jogador |c#GREEN#%s|r.", -- Needs review
	CLEANUP_WILLMSG = "Configura\195\167\195\181es antigas remanescentes para |c#RED#%s|r: %s.", -- Needs review
	CLICKTOSWITCH_INFO = "Se ativado, um clique com o bot\195\163o esquerdo muda os equipamentos, caso contr\195\161rio ele abre a janela do Fishing Buddy", -- Needs review
	CLICKTOSWITCH_ONOFF = "Clique para mudar", -- Needs review
	COMPATIBLE_SWITCHER = "Nenhum equipamento alter\195\161vel compat\195\173vel encontrado", -- Needs review
	CONFIG_ALWAYSLURE_INFO = "Se habilitado, coloca uma isca de cada vez quando a vara n\195\163o tiver nenhuma.", -- Needs review
	CONFIG_ALWAYSLURE_ONOFF = "Sempre com Isca", -- Needs review
	CONFIG_AUTOLOOT_INFO = "Se habilitado, enquanto pesca, a pilhagem autom\195\161tica est\195\161 ligado.", -- Needs review
	CONFIG_AUTOLOOT_ONOFF = "Pilhagem Autom\195\161tica", -- Needs review
	-- CONFIG_AUTOOPEN_INFO = "If enabled, use a double-click to open up fishing quest items.",
	-- CONFIG_AUTOOPEN_ONOFF = "Open quest items",
	CONFIG_BGSOUNDS_INFO = "Se ativado, o som ser\195\161 habilitado enquanto WoW est\195\161 em segundo plano.", -- Needs review
	CONFIG_BGSOUNDS_ONOFF = "Som de fundo", -- Needs review
	-- CONFIG_CONTESTS_INFO = "Display timers for fishing contests.",
	-- CONFIG_CONTESTS_ONOFF = "Fishing contest support",
	-- CONFIG_DERBYTIMER_INFO = "If enabled, display a countdown timer for the start of the Kalu'ak Fishing Derby and a countdown of the time left.",
	-- CONFIG_DERBYTIMER_ONOFF = "Derby timer",
	-- CONFIG_DRINKHEAVILY_INFO = "If enabled, drink #LAGER# whenever you're fishing and 'dry'.",
	-- CONFIG_DRINKHEAVILY_ONOFF = "Drink Lager",
	CONFIG_EASYCAST_INFO = "Ativar o lan\195\167amento com duplo-clique direito", -- Needs review
	CONFIG_EASYCAST_ONOFF = "Lance F\195\161cil", -- Needs review
	CONFIG_EASYLURES_INFO = "Se ativado, uma isca ser\195\161 aplicada \195\160 sua vara de pesca antes de come\195\167ar a pesca, sempre que voc\195\170 precisar de um.", -- Needs review
	CONFIG_EASYLURES_ONOFF = "Iscas F\195\161ceis", -- Needs review
	CONFIG_ENHANCESOUNDS_INFO = "Quando ativado, maximizar o volume de som e minimizar o volume do ambiente para fazer o barulho da b\195\179ia mais percept\195\173vel enquanto pesca.", -- Needs review
	CONFIG_ENHANCESOUNDS_ONOFF = "Melhorar a sons da pesca", -- Needs review
	CONFIG_FINDFISH_INFO = "Ligue a capacidade do 'Busca Peixe' quando vestido para pescar.", -- Needs review
	CONFIG_FINDFISH_ONOFF = "Busca Peixe", -- Needs review
	-- CONFIG_FISHINGBUDDY_INFO = "Bring out that special buddy while you fish.",
	-- CONFIG_FISHINGBUDDY_ONOFF = "Fishing Buddy",
	-- CONFIG_FISHINGFLUFF_INFO = "Enable all sorts of fun while you fish.",
	-- CONFIG_FISHINGFLUFF_ONOFF = "Fishing Fun",
	CONFIG_FISHWATCH_INFO = "Exibir um texto sobreposto com o peixe pescado no local atual.", -- Needs review
	CONFIG_FISHWATCHONLY_INFO = "Mostrar apenas o Observador Peixes quando estamos realmente pescando", -- Needs review
	CONFIG_FISHWATCHONLY_ONOFF = "Somente enquanto pesca", -- Needs review
	CONFIG_FISHWATCH_ONOFF = "Observador de peixes", -- Needs review
	CONFIG_FISHWATCHPERCENT_INFO = "Exibir a porcentagem de cada tipo de peixe no visor do rel\195\179gio.", -- Needs review
	CONFIG_FISHWATCHPERCENT_ONOFF = "Exibir percentagens", -- Needs review
	CONFIG_FISHWATCHSKILL_INFO = "Mostrar a habilidade de pesca atuais e mods na \195\161rea de visualiza\195\167\195\163o de peixes", -- Needs review
	CONFIG_FISHWATCHSKILL_ONOFF = "Habilidade atual", -- Needs review
	CONFIG_FISHWATCHTIME_INFO = "Mostrar a quantidade de tempo desde a \195\186ltima vez que uma vara de pesca foi equipada", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Mostrar o tempo decorrido", -- Needs review
	CONFIG_FISHWATCHZONE_INFO = "Mostrar a zona atual na \195\161rea de visualiza\195\167\195\163o de peixes.", -- Needs review
	CONFIG_FISHWATCHZONE_ONOFF = "Zona atual", -- Needs review
	-- CONFIG_LASTRESORT_INFO = "If enabled, add the biggest lure we have even if it doesn't get us to 100% chance of a catch.",
	-- CONFIG_LASTRESORT_ONOFF = "Lure of last resort",
	-- CONFIG_MAXSOUND_INFO = "If enabled, set the sound volume to the maximum while fishing.",
	-- CONFIG_MAXSOUND_ONOFF = "Full Volume",
	CONFIG_MINIMAPBUTTON_INFO = "Exibir um \195\173cone de #NAME# no mini-mapa.", -- Needs review
	CONFIG_MINIMAPBUTTON_ONOFF = "Mostrar \195\173cone no mini-mapa", -- Needs review
	-- [" CONFIG_MINIMAPMOVE_INFO"] = "If enabled, the minimap icon can be moved by dragging.",
	-- [" CONFIG_MINIMAPMOVE_ONOFF"] = "Draggable",
	-- CONFIG_MOUNTEDCAST_INFO = "If enabled, allow casting while mounted.",
	-- CONFIG_MOUNTEDCAST_ONOFF = "Mounted",
	-- CONFIG_ONLYMINE_INFO = "If enabled, easy cast will only check for your outfit's fishing pole (i.e. it won't search all possible poles for a match).",
	-- CONFIG_ONLYMINE_ONOFF = "Outfit Pole Only",
	-- CONFIG_OUTFITTER_TEXT = "Outfit skill bonus: %s#BR#Draznar's style score: %d ",
	-- CONFIG_SHOWLOCATIONZONES_INFO = "Display both zones and subzones.",
	-- CONFIG_SHOWLOCATIONZONES_ONOFF = "Show Zones",
	-- CONFIG_SHOWNEWFISHIES_INFO = "Display a message in the chat area when a new fish for the current location is caught.",
	-- CONFIG_SHOWNEWFISHIES_ONOFF = "Show new fish",
	-- CONFIG_SHOWPOOLS_INFO = "If enabled, known pool locations will be displayed on the minimap.",
	-- CONFIG_SHOWPOOLS_ONOFF = "Show pools",
	-- CONFIG_SORTBYPERCENT_INFO = "Order displays by the number of fish caught instead of by name.",
	-- CONFIG_SORTBYPERCENT_ONOFF = "Sort by number caught",
	-- CONFIG_SPARKLIES_INFO = "If enabled, the 'sparkles' on fishing pools will be more visible while fishing.",
	-- CONFIG_SPARKLIES_ONOFF = "Enhance Pools",
	-- CONFIG_STVPOOLSONLY_INFO = "If enabled, easy cast will only be enabled if the cursor is over a fishing hole.",
	-- CONFIG_STVPOOLSONLY_ONOFF = "Only cast in pools",
	-- CONFIG_STVTIMER_INFO = "If enabled, display a countdown timer for the start of the Fishing Extravaganza and a countdown of the time left.",
	-- CONFIG_STVTIMER_ONOFF = "Extravaganza timer",
	-- CONFIG_TOOLTIPS_INFO = "If enabled, information about caught fish will be displayed in item tooltips.",
	-- CONFIG_TOOLTIPS_ONOFF = "Show fishing info in tooltips",
	-- CONFIG_TURNOFFPVP_INFO = "If enabled, PVP will be turned off while a fishing pole is equipped.",
	-- CONFIG_TURNOFFPVP_ONOFF = "Turn off PVP",
	-- CONFIG_TURNONSOUND_INFO = "If enabled, always turn on sounds while fishing.",
	-- CONFIG_TURNONSOUND_ONOFF = "Force sound",
	-- CONFIG_USEACTION_INFO = "If enabled, #NAME# will look for an action bar button to use for casting.",
	-- CONFIG_USEACTION_ONOFF = "Use Action",
	-- CONFIG_WATCHBOBBER_INFO = "If enabled, #NAME# will not cast if the cursor is over the Fishing Bobber.",
	-- CONFIG_WATCHBOBBER_ONOFF = "Watch bobber",
	-- COPPER_COIN = "Copper coin",
	-- CURRENT = "current",
	-- CURRENT_HELP = "|c#GREEN#/fb #CURRENT# #RESET#|r#BRSPCS#Reset the fish caught during the current session.",
	-- DERBY = "Derby",
	-- DESCRIPTION1 = "Keep track of the fish you've caught",
	-- DESCRIPTION2 = "and manage your fishing gear.",
	-- ELAPSED = "Elapsed",
	-- ELDER_CLEARWATER = "Elder Clearwater yells: (%a)+ has won the Kalu'ak Fishing Derby!",
	-- ELEM_WATER = "Elemental Water",
	-- EXTRAVAGANZA = "Extravaganza",
	-- FAILEDINIT = "Did not initialize correctly.",
	-- FATLADYSINGS = "|c#RED#%s is over|r (%d:%02d left)",
	-- FISH = "Fish",
	-- FISHTYPES = "Fish types: %d",
	-- FLOATING_DEBRIS = "Floating Debris",
	-- FLOATING_WRECKAGE = "Floating Wreckage",
	-- FORCE = "force",
	-- GOLD_COIN = "Gold coin",
	-- HELP = "help",
	-- HIDEINWATCHER = "Display this fish in the watcher",
	-- HOURLY = "hourly",
	-- KEYS_ALT_TEXT = "Alt",
	-- KEYS_CTRL_TEXT = "Control",
	-- KEYS_LABEL_TEXT = "Modifiers:",
	-- KEYS_NONE_TEXT = "None",
	-- KEYS_SHIFT_TEXT = "Shift",
	-- LAGER = "Captain Rumsey's Lager",
	-- LEFTCLICKTODRAG = "Left-click to drag",
	-- LOCATIONS_INFO = "Shows where you've caught fish by either Area or Fish Type",
	-- LOCATIONS_TAB = "Locations",
	-- MINIMAPBUTTONPLACEMENT = "Placement",
	-- MINIMAPBUTTONPLACEMENTTOOLTIP = "Allows you to move the #NAME# icon around the minimap.",
	-- MINIMAPBUTTONRADIUS = "Distance",
	-- MINIMAPBUTTONRADIUSTOOLTIP = "Determines how far from the minimap the #NAME# icon should be.",
	-- MINIMUMSKILL = "Minimum skill: %d",
	-- NAME = "Fishing Buddy",
	-- NODATAMSG = "No fishing data available.",
	-- NONEAVAILABLE_MSG = "None available",
	-- NOREALM = "unknown realm",
	-- NOTLINKABLE = "<Item is not linkable>",
	-- NOW = "now",
	-- OFFSET_LABEL_TEXT = "Offset:",
	-- OIL_SPILL = "Oil Spill",
	-- OPTIONS_INFO = "Set #NAME# options",
	-- OPTIONS_TAB = "Options",
	-- OUTFITS = "Outfits",
	-- POINT = "point",
	-- POINTS = "points",
	-- POST_HELP = "You can bind both the window toggle and the outfit#BR#switch command to keys in the \"Key Bindings\" window.",
	-- PRE_HELP = "You can use |c#GREEN#/fishingbuddy|r or |c#GREEN#/fb|r for all commands#BR#|c#GREEN#/fb|r: by itself, toggle the Fishing Buddy window#BR#|c#GREEN#/fb #HELP#|r: display this message",
	-- RANDOM = "Random",
	-- RAW = "Raw",
	-- REPLACE = "replace",
	-- RESET = "reset",
	-- RIGGLE_BASSBAIT = "Riggle Bassbait yells: We have a winner! (%a+) is the Master Angler!",
	-- RIGHTCLICKFORMENU = "Right-click for menu",
	-- ROLE_ADDON_AUTHORS = "AddOn Author of Note",
	-- ROLE_HELP_BUGS = "Bug fixes and coding help",
	-- ROLE_HELP_SUGGESTIONS = "Feature suggestions",
	-- ROLE_TRANSLATE_DEDE = "German translation",
	-- ROLE_TRANSLATE_ESES = "Spanish translation",
	-- ROLE_TRANSLATE_FRFR = "French translation",
	-- ROLE_TRANSLATE_KOKR = "Korean translation",
	-- ROLE_TRANSLATE_PTBR = "Brazilian Portuguese translation",
	-- ROLE_TRANSLATE_RURU = "Russion translation",
	-- ROLE_TRANSLATE_ZHCN = "Simplified Chinese translation",
	-- ROLE_TRANSLATE_ZHTW = "Traditional Chinese translation",
	-- SCHOOL = "School",
	-- SHOWFISHIES = "Show fish",
	-- SHOWFISHIES_INFO = "Display fishing history grouped by fish type.",
	-- SHOWLOCATIONS = "Locations",
	-- SHOWLOCATIONS_INFO = "Display fishing history grouped by area caught.",
	-- SILVER_COIN = "Silver coin",
	-- STVZONENAME = "Stranglethorn Vale",
	-- SWITCH = "switch",
	-- SWITCH_HELP = "|c#GREEN#/fb #SWITCH#|r#BRSPCS#swap outfits (if OutfitDisplayFrame or Outfitter is available)",
	-- THANKS = "Thank you, everyone!",
	-- TIMELEFT = "%s ends in %d:%02d",
	-- TIMER = "timer",
	-- TIMERRESET_HELP = "|c#GREEN#/fb #TIMER# #RESET#|r#BRSPCS#Reset the location of the Extravaganza timer by moving it to#BRSPCS#the middle of the screen.",
	-- TIMETOGO = "%s starts in %d:%02d",
	-- TOOLTIP_HINT = "Hint:",
	-- TOOLTIP_HINTSWITCH = "click to switch outfits",
	-- TOOLTIP_HINTTOGGLE = "click to show the #NAME# window.",
	-- TOOMANYFISHERMEN = "You have more than one easy cast mod installed.",
	-- TOTAL = "Total",
	-- TOTALS = "Totals",
	-- UPDATE = "update",
	-- UPDATEDB = "updatedb",
	-- UPDATEDB_HELP = "|c#GREEN#/fb #UPDATEDB# [#FORCE#]|r#BRSPCS#Try and find the names of all the fish we don't know already.#BRSPCS#An attempt is made to skip 'rare' fish that may disconnect you#BRSPCS#from the server -- use the '#FORCE#' option to override the check.",
	-- UPDATEDB_MSG = "Updated %d fish names.",
	-- WATCHER = "watcher",
	-- WATCHER_HELP = "|c#GREEN#/fb #WATCHER#|r [|c#GREEN##WATCHER_LOCK#|r or |c#GREEN##WATCHER_UNLOCK#|r or |c#GREEN##RESET#|r]#BRSPCS#Unlock the watcher to move the window,#BRSPCS#lock to stop, reset to reset",
	-- WATCHER_LOCK = "lock",
	-- WATCHER_TAB = "Watcher",
	-- WATCHER_UNLOCK = "unlock",
	-- WEEKLY = "weekly",
}
