-- Brazilian Portuguese, nomadbr on CurseForge

FishingTranslations["ptBR"] = {
	ADD = "adicionar", -- Needs review
	ADDFISHIEMSG = "Adicionado %s para a localização %s.", -- Needs review
	ADDSCHOOLMSG = "Adicionado '%s' para a localização %s.", -- Needs review
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "Vista-se e vá pescar", -- Needs review
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Mudar equipamento de pesca", -- Needs review
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Alternar a Janela  #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Alternar o Painel de Localização #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Alternar o Painel de Opções #NAME#", -- Needs review
	BOBBER_NAME = "Isca de Pesca", -- Needs review
	CAST = "lançar", -- Needs review
	CAUGHTTHISMANY = "Capturados:", -- Needs review
	CAUGHTTHISTOTAL = "Total:", -- Needs review
	CAUGHT_IN_ZONES = "Capturados em: %s", -- Needs review
	CHECK = "verificar", -- Needs review
	CLEANUP = "limpeza", -- Needs review
	CLEANUP_DONEMSG = "Configurações antigas removidas para |c#RED#%s|r: %s.", -- Needs review
	CLEANUP_NONEMSG = "Nenhuma configuração antiga permanece.", -- Needs review
	CLEANUP_NOOLDMSG = "Não há configurações antigas para o jogador |c#GREEN#%s|r.", -- Needs review
	CLEANUP_WILLMSG = "Configurações antigas remanescentes para |c#RED#%s|r: %s.", -- Needs review
	CLICKTOSWITCH_INFO = "Se ativado, um clique com o botão esquerdo muda os equipamentos, caso contrário ele abre a janela do Fishing Buddy", -- Needs review
	CLICKTOSWITCH_ONOFF = "Clique para mudar", -- Needs review
	COMPATIBLE_SWITCHER = "Nenhum equipamento alterável compatível encontrado", -- Needs review
	CONFIG_ALWAYSLURE_INFO = "Se habilitado, coloca uma isca de cada vez quando a vara não tiver nenhuma.", -- Needs review
	CONFIG_ALWAYSLURE_ONOFF = "Sempre com Isca", -- Needs review
	CONFIG_AUTOLOOT_INFO = "Se habilitado, enquanto pesca, a pilhagem automática está ligado.", -- Needs review
	CONFIG_AUTOLOOT_ONOFF = "Pilhagem Automática", -- Needs review
	CONFIG_BGSOUNDS_INFO = "Se ativado, o som será habilitado enquanto WoW está em segundo plano.", -- Needs review
	CONFIG_BGSOUNDS_ONOFF = "Som de fundo", -- Needs review
	CONFIG_EASYCAST_INFO = "Ativar o lançamento com duplo-clique direito", -- Needs review
	CONFIG_EASYCAST_ONOFF = "Lance Fácil", -- Needs review
	CONFIG_EASYLURES_INFO = "Se ativado, uma isca será aplicada à sua vara de pesca antes de começar a pesca, sempre que você precisar de um.", -- Needs review
	CONFIG_EASYLURES_ONOFF = "Iscas Fáceis", -- Needs review
	CONFIG_ENHANCESOUNDS_INFO = "Quando ativado, maximizar o volume de som e minimizar o volume do ambiente para fazer o barulho da bóia mais perceptível enquanto pesca.", -- Needs review
	CONFIG_ENHANCESOUNDS_ONOFF = "Melhorar a sons da pesca", -- Needs review
	CONFIG_FINDFISH_INFO = "Ligue a capacidade do 'Busca Peixe' quando vestido para pescar.", -- Needs review
	CONFIG_FINDFISH_ONOFF = "Busca Peixe", -- Needs review
	CONFIG_FISHWATCHONLY_INFO = "Mostrar apenas o Observador Peixes quando estamos realmente pescando", -- Needs review
	CONFIG_FISHWATCHONLY_ONOFF = "Somente enquanto pesca", -- Needs review
	CONFIG_FISHWATCHPERCENT_INFO = "Exibir a porcentagem de cada tipo de peixe no visor do relógio.", -- Needs review
	CONFIG_FISHWATCHPERCENT_ONOFF = "Exibir percentagens", -- Needs review
	CONFIG_FISHWATCHSKILL_INFO = "Mostrar a habilidade de pesca atuais e mods na área de visualização de peixes", -- Needs review
	CONFIG_FISHWATCHSKILL_ONOFF = "Habilidade atual", -- Needs review
	CONFIG_FISHWATCHTIME_INFO = "Mostrar a quantidade de tempo desde a última vez que uma vara de pesca foi equipada", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Mostrar o tempo decorrido", -- Needs review
	CONFIG_FISHWATCHZONE_INFO = "Mostrar a zona atual na área de visualização de peixes.", -- Needs review
	CONFIG_FISHWATCHZONE_ONOFF = "Zona atual", -- Needs review
	CONFIG_FISHWATCH_INFO = "Exibir um texto sobreposto com o peixe pescado no local atual.", -- Needs review
	CONFIG_FISHWATCH_ONOFF = "Observador de peixes", -- Needs review
	CONFIG_MINIMAPBUTTON_INFO = "Exibir um ícone de #NAME# no mini-mapa.", -- Needs review
	CONFIG_MINIMAPBUTTON_ONOFF = "Mostrar ícone no mini-mapa", -- Needs review
}
