--German Localization
local _, me = ...

me:NewL({
	professions        = "Berufe",
	cds                = "Abklingzeiten",
	nocds              = "Alle Bereit",
	resetcds           = "Reset CDs",
	settings           = "Einstellungen",
	quicklaunch        = "Quicklaunch",
	tooltips           = "Tooltips",
	ShowAllTooltips    = "Alle Tooltips anzeigen",
	showcds            = "Abklingzeiten",
	showbuttons        = "Tasten",
	bothfactions       = "CDs und Berufe beider Fraktionen anzeigen",
	leftclick          = "Linksklick",
	rightclick         = "Rechtsklick",
	shift              = "Umschalt",
	alt                = "ALT",
	ctrl               = "STRG",
	exchangeleftright  = "Vertausche Maustasten",
	openmenu           = "Menü öffnen",
	infight            = "Du bist im Kampf!",
	otherchar          = "Anderere Charaktere",
	linktome           = "Mir selber linken",
	linktoother        = "In Chat verlinken",
	quicklauncher      = "Separate Quicklauncher",
	deletechartooltip  = "|cffff0000Achtung:|r Löscht alle Einstellungen des Charakters!",
	relog              = "Relog wird benötigt!",
	possiblereagents   = "Warscheinlichste Reagenzien",
	autoloot           = " (+ Autoloot)",
	filter             = "Berufe ausblenden",
	nomats             = "Keine Mats",
	ShowIfYouCanCraftThisInItemTooltips = "Zeige in Item Tooltips, ob du es herstellen kannst.",
	--shared cds
	transmute          = "Alchemie: Transmutieren",
	--favorites
	favorites          = "Favoriten",
	showfavorites      = "Favoriten anzeigen",
	nofavorites        = "Keine Favoriten angelegt!\nÖffne das Berufsfenster und Rechtsklicke auf deine Tradeskills um sie hinzuzufügen.",
	addtofav		 		 = "Zu den Favoriten hinzufügen.",
	removefromfav		 = "Von den Favoriten entfernen.",
	--trainer
	trainer            = "Lehrer",
	knowallrecipes     = "|cffffcf00Alle Rezepte bereits gelernt|r",
	databaseempty      = "Datenbank leer",
	visityourtrainer   = "Besuche deinen |cff00ff00%s|r Lehrer",
	trainerdisabled    = "Lehrer Fenster deaktivieren",
},"deDE")