--English Localization
local _, me = ...

me:NewL({
	professions        = "Professions",
	cds                = "Cooldowns",
	nocds              = "All Ready",
	resetcds           = "Reset CDs",
	settings           = "Settings",
	quicklaunch        = "Quicklaunch",
	tooltips           = "Tooltips",
	ShowAllTooltips    = "Show all tooltips",
	showcds            = "Cooldowns",
	showbuttons        = "Buttons",
	bothfactions       = "Show CDs und Tradeskills of both factions",
	leftclick          = "Left Click",
	rightclick         = "Right Click",
	shift              = "Shift",
	alt                = "ALT",
	ctrl               = "CTRL",
	exchangeleftright  = "Exchange Mousebuttons",
	openmenu           = "Open Menu",
	infight            = "You are in fight!",
	otherchar          = "Other Characters",
	linktome           = "Link to me",
	linktoother        = "Link to chat",
	quicklauncher      = "Separate Quicklaunchers",
	deletechartooltip  = "|cffff0000Attention:|r Clears all settings of this character!",
	relog              = "Relog is required!",
	possiblereagents   = "Possible Reagents",
	autoloot           = " (+ Autoloot)",
	filter             = "Hide tradeskills",
	nomats             = "No Mats",
	ShowIfYouCanCraftThisInItemTooltips = "Show in item tooltips, if you can craft this.",
	--shared cds
	transmute          = "Alchemy: Transmute",
	--favorites
	favorites          = "Favorites",
	showfavorites      = "Show Favorites",
	nofavorites        = "No favorites createt!\nOpen tradeskill window and right-click on your tradeskills to create favorites.",
	addtofav		 		 = "Right-Click: Add to favorites.",
	removefromfav		 = "Right-Click: Remove from favorites.",
	--trainer
	trainer            = "Trainer",
	knowallrecipes     = "|cffffcf00All recipes already learned|r",
	databaseempty      = "Database empty",
	visityourtrainer   = "Visit your |cff00ff00%s|r trainer",
	trainerdisabled    = "Disable trainer frame",
})