--Simplified Chinese localization by haidaodou
local _, me = ...

me:NewL({
	-- addtofav = "Right-Click: Add to favorites.",
	alt = "ALT",
	autoloot = " (+ 自动拾取)",
	bothfactions = "显示两边阵营专业技能和冷却",
	cds = "冷却中",
	ctrl = "CTRL",
	databaseempty = "空数据库",
	deletechartooltip = "|cffff0000注意:|r 清除本角色所有设置!",
	exchangeleftright = "互换鼠标按键",
	favorites = "收藏夹",
	filter = "隐藏专业技能",
	infight = "你在战斗中!",
	knowallrecipes = "|cffffcf00所有配方都已学会|r",
	leftclick = "左键点击",
	linktome = "发送到自身",
	linktoother = "发送到聊天框",
	nocds = "准备就绪",
	nofavorites = "还未创建收藏夹",
	-- nomats = "No Mats",
	openmenu = "打开选项菜单",
	otherchar = "其他角色",
	possiblereagents = "可能得到的物品",
	professions = "专业技能",
	quicklaunch = "快速启动",
	quicklauncher = "独立显示于信息条",
	relog = "需要重载插件!",
	-- removefromfav = "Right-Click: Remove from favorites.",
	resetcds = "重置冷却",
	rightclick = "右键点击",
	settings = "设置",
	shift = "Shift",
	ShowAllTooltips = "显示所有鼠标提示",
	showbuttons = "按键说明",
	showcds = "冷却状态",
	showfavorites = "显示收藏夹",
	-- ShowIfYouCanCraftThisInItemTooltips = "Show in item tooltips, if you can craft this.",
	tooltips = "鼠标提示",
	trainer = "训练师",
	trainerdisabled = "禁用训练师扩展界面",
	transmute = "炼金术: 转化",
	visityourtrainer = "请访问你的 |cff00ff00%s|r 训练师",
},"zhCN")