--Traditional Chinese localization by haidaodou
local _, me = ...

me:NewL({
	-- addtofav = "Right-Click: Add to favorites.",
	alt = "ALT",
	autoloot = " (+ 自動拾取)",
	bothfactions = "顯示兩邊陣營的專業技能和冷卻",
	cds = "冷卻中",
	ctrl = "CTRL",
	databaseempty = "空數據庫",
	deletechartooltip = "|cffff0000注意:|r 清除本角色所有設置!",
	exchangeleftright = "互換滑鼠按鍵",
	favorites = "收藏夾",
	filter = "隱藏專業技能",
	infight = "你在戰鬥中!",
	knowallrecipes = "|cffffcf00所有配方都已學會|r",
	leftclick = "左鍵點擊",
	linktome = "發送到自身",
	linktoother = "發送到聊天框",
	nocds = "準備就緒",
	nofavorites = "還未創建收藏夾",
	-- nomats = "No Mats",
	openmenu = "打開選項菜單",
	otherchar = "其他角色",
	possiblereagents = "可能得到的物品",
	professions = "專業技能",
	quicklaunch = "快速啟動",
	quicklauncher = "獨立顯示於信息條",
	relog = "需要重新加載插件",
	-- removefromfav = "Right-Click: Remove from favorites.",
	resetcds = "重置冷卻",
	rightclick = "右鍵點擊",
	settings = "設置",
	shift = "Shift",
	ShowAllTooltips = "顯示所有訊息提示",
	showbuttons = "按鍵說明",
	showcds = "冷卻狀態",
	showfavorites = "顯示收藏夾",
	-- ShowIfYouCanCraftThisInItemTooltips = "Show in item tooltips, if you can craft this.",
	tooltips = "滑鼠訊息提示",
	trainer = "訓練師",
	trainerdisabled = "禁用訓練師擴展介面",
	transmute = "煉金術: 轉化",
	visityourtrainer = "請訪問你的 |cff00ff00%s|r 訓練師",
},"zhTW")