-- THE CONTENTS OF THIS FILE ARE AUTO-GENERATED
-- Please help contribute translations with the WowAce Localization app
-- at http://www.wowace.com/addons/scorchio2/localization/

local addonName = "Scorchio2_Options"
local AL3 = LibStub("AceLocale-3.0")
local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local LO = AL3:NewLocale(addonName, "enUS", true, debug)
if LO then
LO["Alpha"] = true
LO["Alpha applied to bar"] = true
LO["Alpha applied to Non-Target bars"] = true
LO["Alpha applied to Target bar"] = true
LO["Anchor"] = true
LO["Anchor Options"] = true
LO["Anchor used for %s bar"] = true
LO["Anchor used when %s is on something NOT your target"] = true
LO["Anchor used when %s is on your target"] = true
LO["Background Colour"] = true
LO["Bar Colour"] = true
LO["Bar Options"] = true
LO["Bar Text"] = true
LO["Buffs"] = true
LO["Change background colour"] = true
LO["Change bar colour"] = true
LO["Change the font size"] = true
LO["Change the height of the bars"] = true
LO["Change the scale of the bars"] = true
LO["Change the sound played when %s expires."] = true
LO["Change the sound played when %s procs."] = true
LO["Change the sound played when warning time is reached"] = true
LO["Change the texture of the bars"] = true
LO["Change the width of the bars"] = true
LO["Change which way the bars run"] = true
LO["Classic Anchors"] = true
LO["Enable/Disable sounds for %s"] = true
LO["Enter message to appear when %s is ready."] = true
LO["Enter message to appear when %s procs"] = true
LO["Enter text to appear on %s bars."] = true
LO["Enter warning to appear when %s expires."] = true
LO["Enter warning to appear when %s will fade."] = true
LO["Expired Sound"] = true
LO["Expired Text"] = true
LO["Fade bars when out of combat"] = true
LO["Font"] = true
LO["Font Size"] = true
LO["Grow Up"] = true
LO["Height"] = true
LO["Hide OOC"] = true
LO["If checked, bars will stack above the anchor, not below"] = true
LO["Left to Right"] = true
LO["Max Bars"] = true
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = true
LO["Modern Anchors"] = true
LO["My Target Only"] = true
LO["None"] = true
LO["Non-Target Alpha"] = true
LO["Non-Target Anchor"] = true
LO["Non-Targeted"] = true
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = true
LO["Orientation"] = true
LO["Proc Sound"] = true
LO["Proc Text"] = true
LO["Ready Text"] = true
LO["Reset Anchors"] = true
LO["Reset bars to their default positions on the screen"] = true
LO["Restore Custom"] = true
LO["Restored 'Custom Anchors' Preset"] = true
LO["(Restores your saved configuration.)"] = true
LO["Right to Left"] = true
LO["Save Custom"] = true
LO["Saved 'Custom Anchors' Preset"] = true
LO["(Saves your current configuration.)"] = true
LO["(Saves your current configuration, or restores a saved one.)"] = true
LO["Scale"] = true
LO["Set the bar font"] = true
LO["Show Bars"] = true
LO["Show bars for %s"] = true
LO["Show Expired Notices"] = true
LO["Show message when someone breaks %s early"] = true
LO["Show message when %s procs"] = true
LO["Show notice when spell expires"] = true
LO["Show Proc"] = true
LO["Shows/Hides the draggable anchor"] = true
LO["Shows test bars"] = true
LO["Show Warnings"] = true
LO["Show warning when spell is about to expire"] = true
LO["Show Who Broke It"] = true
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = true
LO["Target Alpha"] = true
LO["Target Anchor"] = true
LO["Targeted"] = true
LO["Test"] = true
LO["Texture"] = true
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = true
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = true
LO["Toggle Anchor"] = true
LO["Toggle Sounds"] = true
LO["Track %s"] = true
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = true
LO["Warning Sound"] = true
LO["Warning Text"] = true
LO["Warning Time"] = true
LO["Warning Time for %s"] = true
LO["Width"] = true

if GetLocale() == "enUS" or GetLocale() == "enGB" then return end
end

local LO = AL3:NewLocale(addonName, "deDE")
if LO then
LO["Alpha"] = "Transparenz"
LO["Alpha applied to bar"] = "Transparenz auf den Leisten angewendet."
LO["Alpha applied to Non-Target bars"] = "Transparenz auf Non-Target Leisten angewendet."
LO["Alpha applied to Target bar"] = "Transparenz auf Ziel Leisten angewendet."
LO["Anchor"] = "Anker"
LO["Anchor Options"] = "Ankeroptionen"
LO["Anchor used for %s bar"] = "Anker für die Leiste von %s verwendet."
LO["Anchor used when %s is on something NOT your target"] = "Anker der verwendet wird, wenn %s auf etwas ist, was NICHT Dein Ziel ist."
LO["Anchor used when %s is on your target"] = "Anker der verwendet wird, wenn %s auf Deinem Ziel ist."
LO["Background Colour"] = "Hintergrundfarbe"
LO["Bar Colour"] = "Leistenfarbe"
LO["Bar Options"] = "Balken Optionen"
LO["Bar Text"] = "Leistentext"
LO["Buffs"] = "Verstärkungszauber \"Buff\""
LO["Change background colour"] = "ändert die Huntergrundfarbe"
LO["Change bar colour"] = "ändert dieBalkenfarbe"
LO["Change the font size"] = "ändert den Schriftgrad"
LO["Change the height of the bars"] = "Die Höhe der Leisten ändern"
LO["Change the scale of the bars"] = "Die Skalierung der Leisten ändern"
LO["Change the sound played when %s expires."] = "Den Sound ändern, der abgespielt wird, wenn %s ausläuft."
LO["Change the sound played when %s procs."] = "Den Sound ändern, der abgespielt wird wenn %s proct."
LO["Change the sound played when warning time is reached"] = "Den Sound ändern, der abgespielt wird wenn das Zeitlimit erreicht wurde."
LO["Change the texture of the bars"] = "Die Textur der Leisten ändern"
LO["Change the width of the bars"] = "Die Breite der Leisten ändern"
LO["Change which way the bars run"] = "Ändert der Richtung wie die Leisten verlaufen."
LO["Classic Anchors"] = "Klassische Anker"
LO["Enable/Disable sounds for %s"] = "Sounds für %s aktivieren/deaktivieren."
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "Bitte eine Meldung eingeben, die bei %s erscheinen soll."
LO["Enter text to appear on %s bars."] = "Bitte einen Text eingeben, der auf Leisten von %s erscheinen soll."
LO["Enter warning to appear when %s expires."] = "Bitte eine Warnung eingeben, die beim Auslaufen von %s erscheint."
LO["Enter warning to appear when %s will fade."] = "Bitte eine Warnung eingeben, die beim Verblassen von %s erscheint."
LO["Expired Sound"] = "Sound für abgelaufen"
LO["Expired Text"] = "Text für abgelaufen"
LO["Fade bars when out of combat"] = "Leisten verblassen, wenn außerhalb des Kampfes."
LO["Font"] = "Schriftart"
LO["Font Size"] = "Schriftgröße"
LO["Grow Up"] = "Aufwärts wachsen" -- Needs review
LO["Height"] = "Höhe"
LO["Hide OOC"] = "Verstecke außerhalb des Kampfes "
LO["If checked, bars will stack above the anchor, not below"] = "Wenn aktiviert, werden sich die Leisten nach oben stapeln und nicht hinunter."
LO["Left to Right"] = "Links nach Rechts"
LO["Max Bars"] = "Max. Leisten"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "Maximale Anzahl an Leisten, die angezeigt werden. Auf 0 setzen, um alle Leisten anzuzeigen."
LO["Modern Anchors"] = "Moderne Anker" -- Needs review
LO["My Target Only"] = "Nur mein Ziel."
LO["None"] = "Keine"
LO["Non-Target Alpha"] = "Nicht-Ziel Alpha"
LO["Non-Target Anchor"] = "Nicht-Ziel Anker"
LO["Non-Targeted"] = "Nicht-Ziele"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "(Ein Anker: Gezielte Balken von Non-targeted Mobs sind ausgeblendet.)" -- Needs review
LO["Orientation"] = "Ausrichtung"
LO["Proc Sound"] = "Sound für Proc"
LO["Proc Text"] = "Proc Text"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "Anker zurücksetzen"
LO["Reset bars to their default positions on the screen"] = "Die Leisten auf ihre standardmäßigen Positionen zurücksetzen."
LO["Restore Custom"] = "Benutzerdefinierte wiederherstellen"
LO["Restored 'Custom Anchors' Preset"] = "Wiederherstellen der 'Benutzerdefinierte Anker' Voreinstellung" -- Needs review
LO["(Restores your saved configuration.)"] = "Stellt deine gespeicherten Einstellungen wieder her."
LO["Right to Left"] = "Rechts nach Links"
LO["Save Custom"] = "Benutzerdefinierte speichern"
LO["Saved 'Custom Anchors' Preset"] = "'Benutzerdefinerte Anker' gespeichert"
LO["(Saves your current configuration.)"] = "Speichert deine derzeitigen Einstellungen"
LO["(Saves your current configuration, or restores a saved one.)"] = "Speichert deine derzeitigen Einstellungen, oder stellt gespeicherte wieder her."
LO["Scale"] = "Skalierung"
LO["Set the bar font"] = "Die Schriftart der Leisten festlegen."
LO["Show Bars"] = "Zeige Leisten"
LO["Show bars for %s"] = "Zeige Leisten für %s"
LO["Show Expired Notices"] = "Abgelaufene Hinweise anzeigen"
LO["Show message when someone breaks %s early"] = "Meldung anzeigen, wenn jemand zu Früh %s bricht."
LO["Show message when %s procs"] = "Nachricht anzeigen, wenn %s geproct ist."
LO["Show notice when spell expires"] = "Hinweis anzeigen, wenn ein Zauber ausläuft."
LO["Show Proc"] = "Procs anzeigen"
LO["Shows/Hides the draggable anchor"] = "Ein/Ausblenden der ziehbaren Anker."
LO["Shows test bars"] = "Zeige Testleisten"
LO["Show Warnings"] = "Zeige Warnungen"
LO["Show warning when spell is about to expire"] = "Warnungen anzeigen, wenn ein Zauber bald ausläuft."
LO["Show Who Broke It"] = "Zeige wer unterbrochen hat"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s wird durch den Zauber Stapel ersetzt werden. $m wird durch den Mob Namen ersetzt. Alles andere bleibt wie es ist." -- Needs review
LO["Target Alpha"] = "Ziel Alpha"
LO["Target Anchor"] = "Ziel Anker"
LO["Targeted"] = "Anvisiert"
LO["Test"] = "Test"
LO["Texture"] = "Textur"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "Diese Voreinstellungen speichern nur Informationen für Anker und Transparenz. Wenn Du eine gesamte Konfiguration speichern möchtest (beinhaltet Leistenfarben, Akustische Warnung, etc.), verwende bitte das Profil Feature."
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "(Drei Anker:.. Gezielte, nicht zielgerichtete und Buffs. Alle Alphas 1.0)" -- Needs review
LO["Toggle Anchor"] = "Anker ein-/ausblenden"
LO["Toggle Sounds"] = "Sounds ein-/ausschalten"
LO["Track %s"] = "%s verfolgen"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "(Zwei Anker: Gezielte und Buffs nur zeigen Debuffs auf mein Ziel.)" -- Needs review
LO["Warning Sound"] = "Akustische Warnung"
LO["Warning Text"] = "Textwarnung"
LO["Warning Time"] = "Zeitliche Warnung" -- Needs review
LO["Warning Time for %s"] = "Alarmzeit für %s"
LO["Width"] = "Breite"

return
end

local LO = AL3:NewLocale(addonName, "esES") or AL3:NewLocale(addonName, "esMX")
if LO then
LO["Alpha"] = "Alfa"
LO["Alpha applied to bar"] = "Alfa aplicada a la barra"
LO["Alpha applied to Non-Target bars"] = "Alfa aplicada a barra de otros objetivos"
LO["Alpha applied to Target bar"] = "Alfa aplicada a barra de objetivo actual"
LO["Anchor"] = "Punto de anclaje"
LO["Anchor Options"] = "Opciones de punto de anclaje"
LO["Anchor used for %s bar"] = "Punto de anclaje usado para barra de %s"
LO["Anchor used when %s is on something NOT your target"] = "Punto de anclaje usado cuando %s está activo en algo que NO sea tu objetivo actual"
LO["Anchor used when %s is on your target"] = "Punto de anclaje usado cuando %s está activo en tu objetivo actual"
LO["Background Colour"] = "Color de fondo"
LO["Bar Colour"] = "Color de la barra"
LO["Bar Options"] = "Opciones de barras"
LO["Bar Text"] = "Texto de la barra"
LO["Buffs"] = "Auras"
LO["Change background colour"] = "Cambiar color de fondo"
LO["Change bar colour"] = "Cambiar color de barra"
LO["Change the font size"] = "Cambiar tamaño de fuente"
LO["Change the height of the bars"] = "Cambiar altura de barra"
LO["Change the scale of the bars"] = "Cambiar escala de barra"
LO["Change the sound played when %s expires."] = "Cambiar el sonido que avisa de que %s ha expirado."
LO["Change the sound played when %s procs."] = "Cambiar el sonido de activación de %s."
LO["Change the sound played when warning time is reached"] = "Cambiar el sonido de aviso."
LO["Change the texture of the bars"] = "Cambiar textura de barras."
LO["Change the width of the bars"] = "Cambiar anchura de barras"
LO["Change which way the bars run"] = "Cambia hacia dónde se desplazan las barras"
LO["Classic Anchors"] = "Estilo de columnas clásico"
LO["Enable/Disable sounds for %s"] = "Activar/desactivar sonidos para %s"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "Introduce el mensaje que aparecerá cuando se active %s"
LO["Enter text to appear on %s bars."] = "Introduce el texto que aparecerá en las barras de %s"
LO["Enter warning to appear when %s expires."] = "Introduce el aviso que aparecerá cuando expire %s"
LO["Enter warning to appear when %s will fade."] = "Introduce el aviso que aparecerá cuando %s se desvanezca"
LO["Expired Sound"] = "Sonido de finalización"
LO["Expired Text"] = "Texto de finalización"
LO["Fade bars when out of combat"] = "No mostrar las barras fuera de combate"
LO["Font"] = "Fuente"
LO["Font Size"] = "Tamaño de fuente"
LO["Grow Up"] = "Apilar barras sobre el punto de anclaje"
LO["Height"] = "Altura"
LO["Hide OOC"] = "Ocultar barras fuera de combate"
LO["If checked, bars will stack above the anchor, not below"] = "Si está marcada, las barras se apilarán sobre el punto de anclaje, no bajo él"
LO["Left to Right"] = "De izquierda a derecha"
LO["Max Bars"] = "Número máximo de barras"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "Máximo número de barras que se muestran simultáneamente. Poner a 0 para mostrarlas todas."
LO["Modern Anchors"] = "Estilo de columnas moderno."
LO["My Target Only"] = "Mi objetivo sólo"
LO["None"] = "Ninguno"
LO["Non-Target Alpha"] = "Alfa de otros objetivos"
LO["Non-Target Anchor"] = "Punto de anclaje de otros objetivos"
LO["Non-Targeted"] = "Otros objetivos"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "(Una columna: Objetivo actual. Las barras para el resto de monstruos se muestran más claras)"
LO["Orientation"] = "Orientación"
LO["Proc Sound"] = "Sonido de activación"
LO["Proc Text"] = "Texto de activación"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "Restaurar puntos de anclaje"
LO["Reset bars to their default positions on the screen"] = "Restaura las barras a sus posiciones por defecto"
LO["Restore Custom"] = "Restaurar columnas por defecto"
LO["Restored 'Custom Anchors' Preset"] = "Columnas por defecto restauradas"
LO["(Restores your saved configuration.)"] = "(Restaura tu configuración guardada.)"
LO["Right to Left"] = "De derecha a izquierda"
LO["Save Custom"] = "Guardar como modelo"
LO["Saved 'Custom Anchors' Preset"] = "Puntos de anclaje por defecto guardados"
LO["(Saves your current configuration.)"] = "(Guarda tu configuración actual.)"
LO["(Saves your current configuration, or restores a saved one.)"] = "(Guarda tu configuración actual, o restaura una grabada.)"
LO["Scale"] = "Escala"
LO["Set the bar font"] = "Cambiar la fuente de la barra"
LO["Show Bars"] = "Mostrar barras"
LO["Show bars for %s"] = "Mostrar barras para %s"
LO["Show Expired Notices"] = "Mostrar texto de finalización"
LO["Show message when someone breaks %s early"] = "Mostrar mensaje cuando alguien rompa %s antes de tiempo"
LO["Show message when %s procs"] = "Mostrar mensaje cuando se active %s"
LO["Show notice when spell expires"] = "Mostrar aviso de expiración de hechizo"
LO["Show Proc"] = "Mostrar texto de activación"
LO["Shows/Hides the draggable anchor"] = "Muestra/Oculta el punto de anclaje deslizable"
LO["Shows test bars"] = "Mostrar barras de test"
LO["Show Warnings"] = "Mostrar avisos"
LO["Show warning when spell is about to expire"] = "Mostrar aviso cuando el hechizo esté a punto de expirar"
LO["Show Who Broke It"] = "Mostrar quién lo ha roto"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s será reemplazado por el hechizo activo. $m será reemplazado por el nombre del monstruo. El resto permanecerá tal cual."
LO["Target Alpha"] = "Alfa del objetivo"
LO["Target Anchor"] = "Punto de anclaje del objetivo"
LO["Targeted"] = "Objetivo"
LO["Test"] = "Test"
LO["Texture"] = "Textura"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "Sólo se guardará la información sobre puntos de anclaje y alfas. Si deseas grabar la configuración completa (incluyendo colores de barra, sonidos de aviso, etc) utiliza la opción \"Perfiles\"."
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "(Tres columnas: Objetivo actual, otros objetivos, y auras. Todos en alfa 1.0.)"
LO["Toggle Anchor"] = "Mostrar/Ocultar punto de anclaje"
LO["Toggle Sounds"] = "Activar/Desactivar sonidos"
LO["Track %s"] = "Seguimiento de %s"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "(Dos columnas: Objetivo actual y auras. Mostrar los perjuicios sólo sobre mi objetivo actual.)"
LO["Warning Sound"] = "Sonido de aviso"
LO["Warning Text"] = "Texto de aviso"
LO["Warning Time"] = "Tiempo de aviso"
LO["Warning Time for %s"] = "Tiempo de aviso para %s"
LO["Width"] = "Anchura"

return
end

local LO = AL3:NewLocale(addonName, "frFR")
if LO then
LO["Alpha"] = "Transparence"
LO["Alpha applied to bar"] = "Transparence appliquée à la barre"
LO["Alpha applied to Non-Target bars"] = "Transparence appliquée aux barres de mobs non ciblés."
LO["Alpha applied to Target bar"] = "Transparence appliquée à la barre de cible"
LO["Anchor"] = "Ancre"
LO["Anchor Options"] = "Option de l'ancre"
LO["Anchor used for %s bar"] = "Ancre utilisée pour la barre de %s"
LO["Anchor used when %s is on something NOT your target"] = "Ancre utilisée quand %s est sur quelque chose qui n'est pas votre cible"
LO["Anchor used when %s is on your target"] = "Ancre utilisée quand %s est sur votre cible"
LO["Background Colour"] = "Couleur de fond"
LO["Bar Colour"] = "Couleur de la barre"
LO["Bar Options"] = "Options de la barre"
LO["Bar Text"] = "Texte de la barre"
LO["Buffs"] = "Buffs"
LO["Change background colour"] = "Change la couleur de fond"
LO["Change bar colour"] = "Change la couleur de la barre"
LO["Change the font size"] = "Change la taille de la police"
LO["Change the height of the bars"] = "Change la hauteur des barres"
LO["Change the scale of the bars"] = "Change l'échelle des barres"
LO["Change the sound played when %s expires."] = "Change le son joué lorsque %s expire."
LO["Change the sound played when %s procs."] = "Change le son  joué quand %s se déclenche."
LO["Change the sound played when warning time is reached"] = "Change le son des avertissements"
LO["Change the texture of the bars"] = "Change la texture des barres."
LO["Change the width of the bars"] = "Change la largeur des barres."
LO["Change which way the bars run"] = "Change le sens de défilement des barres."
LO["Classic Anchors"] = "Ancres classiques"
LO["Enable/Disable sounds for %s"] = "Active / désactive les sons pour %s"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "Entre le message à afficher lorsque %s se déclenche"
LO["Enter text to appear on %s bars."] = "Entre le texte à afficher sur les barres de %s."
LO["Enter warning to appear when %s expires."] = "Entre les avertissements à afficher lorsque %s expire."
LO["Enter warning to appear when %s will fade."] = "Entre les avertissements à afficher lorsque %s va disparaître."
LO["Expired Sound"] = "Son d'expiration"
LO["Expired Text"] = "Texte d'expiration"
LO["Fade bars when out of combat"] = "Transparence des barres hors combat"
LO["Font"] = "Police"
LO["Font Size"] = "Taille de la police"
LO["Grow Up"] = "Ajout des barres vers le haut"
LO["Height"] = "Hauteur"
LO["Hide OOC"] = "Cacher les barres hors combat"
LO["If checked, bars will stack above the anchor, not below"] = "Si coché, les barres vont s'empiler au dessus de l'ancre, pas en dessous."
LO["Left to Right"] = "De gauche à droite"
LO["Max Bars"] = "Nombre maximum de barres"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "Nombre maximum de barres à afficher au même moment. Mettre à 0 pour afficher toutes les barres."
LO["Modern Anchors"] = "Ancres modernes"
LO["My Target Only"] = "Ma cible seulement"
LO["None"] = "Aucun"
LO["Non-Target Alpha"] = "Transparence des barres de mobs non ciblés"
LO["Non-Target Anchor"] = "Ancre des barres de mobs non ciblés"
LO["Non-Targeted"] = "Mobs non ciblés"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "(Ancre 1 : cible. Les bars des mobs non ciblés sont grisées.)"
LO["Orientation"] = "Sens de défilement"
LO["Proc Sound"] = "Son des procs"
LO["Proc Text"] = "Texte des procs"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "Réinitialiser les ancres"
LO["Reset bars to their default positions on the screen"] = "Réinitialiser la position des barres"
LO["Restore Custom"] = "Restaurer les ancres personnalisées"
LO["Restored 'Custom Anchors' Preset"] = "Réglages précédents des ancres personnalisées restaurés."
LO["(Restores your saved configuration.)"] = "(Restaure votre configuration enregistrée.)"
LO["Right to Left"] = "De droite à gauche"
LO["Save Custom"] = "Enregistrer"
LO["Saved 'Custom Anchors' Preset"] = "Ancres personnalisées enregistrées"
LO["(Saves your current configuration.)"] = "(Enregistre votre configuration actuelle.)"
LO["(Saves your current configuration, or restores a saved one.)"] = "(Enregistre votre configuration actuelle, ou restaure une configuration sauvegardée.)"
LO["Scale"] = "Échelle"
LO["Set the bar font"] = "Réglage de la police des barres"
LO["Show Bars"] = "Montrer les barres"
LO["Show bars for %s"] = "Montre les barres pour %s"
LO["Show Expired Notices"] = "Afficher les notifications de fin de sort"
LO["Show message when someone breaks %s early"] = "Affiche un message quand quelqu'un casse %s"
LO["Show message when %s procs"] = "Montre les messages pour les procs de %s"
LO["Show notice when spell expires"] = "Montre un avertissement quand un sort expire"
LO["Show Proc"] = "Montrer les procs"
LO["Shows/Hides the draggable anchor"] = "Affiche / cache les ancres déplaçables"
LO["Shows test bars"] = "Affiche les barres de test"
LO["Show Warnings"] = "Montrer les avertissements"
LO["Show warning when spell is about to expire"] = "Montre un avertissement quand un sort est sur le point d'expirer"
LO["Show Who Broke It"] = "Indiquer qui a cassé la métamorphose"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s sera remplacé par le sort. $m sera remplacé par le nom du mob. Le reste ne sera pas modifié."
LO["Target Alpha"] = "Transparence de la cible"
LO["Target Anchor"] = "Ancre de la cible"
LO["Targeted"] = "Cible"
LO["Test"] = "Tester"
LO["Texture"] = "Texture"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "Ces préréglages enregistrent seulement les réglages de l'ancre et de la transparence. Si vous voulez enregistrer la configuration complète (couleurs des barres, sons d'avertissement, etc...), utilisez les profiles."
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "(Trois ancres : cible, mobs non ciblés et buff. Toutes avec transparence à 1.0.)"
LO["Toggle Anchor"] = "Afficher l'ancre"
LO["Toggle Sounds"] = "Activer les sons"
LO["Track %s"] = "Surveiller %s"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "(Deux ancres : cible et buffs, Montre seulement les debuffs de ma cible.)"
LO["Warning Sound"] = "Sons d'avertissement"
LO["Warning Text"] = "Texte d'avertissement"
LO["Warning Time"] = "Temps d'avertissement"
LO["Warning Time for %s"] = "Timer pour %s"
LO["Width"] = "Largeur"

return
end

local LO = AL3:NewLocale(addonName, "koKR")
if LO then
LO["Alpha"] = "투명도"
-- LO["Alpha applied to bar"] = ""
LO["Alpha applied to Non-Target bars"] = "대상없음 창의 투명도" -- Needs review
LO["Alpha applied to Target bar"] = "대상 창의 투명도" -- Needs review
LO["Anchor"] = "앵커"
LO["Anchor Options"] = "앵커 설정"
-- LO["Anchor used for %s bar"] = ""
-- LO["Anchor used when %s is on something NOT your target"] = ""
-- LO["Anchor used when %s is on your target"] = ""
LO["Background Colour"] = "배경색"
LO["Bar Colour"] = "바 색"
LO["Bar Options"] = "바 설정"
LO["Bar Text"] = "바 문자"
LO["Buffs"] = "버프"
LO["Change background colour"] = "배경색 변경"
LO["Change bar colour"] = "바 색 변경"
LO["Change the font size"] = "글자 크기 변경"
LO["Change the height of the bars"] = "바의 높이 변경"
LO["Change the scale of the bars"] = "바의 크기 변경"
LO["Change the sound played when %s expires."] = "%s 사라질 때 알릴 소리 변경" -- Needs review
LO["Change the sound played when %s procs."] = "%s "
LO["Change the sound played when warning time is reached"] = "경고 시간 도달 시 알림소리 변경"
LO["Change the texture of the bars"] = "바의 택스쳐 변경"
LO["Change the width of the bars"] = "바의 폭 변경"
LO["Change which way the bars run"] = "바의 진행 방향 변경"
-- LO["Classic Anchors"] = ""
LO["Enable/Disable sounds for %s"] = "%s의 소리 켜기/끄기"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "%s 진행시 나타날 메세지 입력"
LO["Enter text to appear on %s bars."] = "%s 바에 나타날 텍스트 입력"
LO["Enter warning to appear when %s expires."] = "%s 끝날 때 알릴 경보 입력"
LO["Enter warning to appear when %s will fade."] = "%s 사라질 때 알릴 경보 입력"
LO["Expired Sound"] = "기술 종료시의 사운드" -- Needs review
LO["Expired Text"] = "기술 종료시의 메세지" -- Needs review
LO["Fade bars when out of combat"] = "전투상태가 아닌 경우 표시하지 않음" -- Needs review
LO["Font"] = "글자체"
LO["Font Size"] = "글자 크기"
LO["Grow Up"] = "위로 진행"
LO["Height"] = "높이"
LO["Hide OOC"] = "전투 종료시 숨기기"
LO["If checked, bars will stack above the anchor, not below"] = "체크 하면 바가 앵커 위로 쌓입니다."
LO["Left to Right"] = "좌에서 우로"
LO["Max Bars"] = "최대 바 갯수"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "한번에 표시 될 바의 최대 갯수 지정. 0으로 설정시 모든 바 보임"
-- LO["Modern Anchors"] = ""
LO["My Target Only"] = "나의 대상만 "
LO["None"] = "없음"
LO["Non-Target Alpha"] = "타겟 없을 때 투명도" -- Needs review
LO["Non-Target Anchor"] = "타겟 없을 때 앵커" -- Needs review
LO["Non-Targeted"] = "타겟 없음"
-- LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = ""
LO["Orientation"] = "방향"
-- LO["Proc Sound"] = ""
-- LO["Proc Text"] = ""
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "앵커 초기화"
LO["Reset bars to their default positions on the screen"] = "바를 화면의 기본위치로 초기화합니다." -- Needs review
LO["Restore Custom"] = "사용자 정의 설정 복구"
LO["Restored 'Custom Anchors' Preset"] = "'사용자 정의 앵커' 프리셋 복원"
LO["(Restores your saved configuration.)"] = "(저장된 설정을 복구합니다)" -- Needs review
LO["Right to Left"] = "우에서 좌로"
LO["Save Custom"] = "사용자 정의 앵커 저장"
LO["Saved 'Custom Anchors' Preset"] = "'사용자 정의 앵커' 프리셋 저장됨"
LO["(Saves your current configuration.)"] = "(현재 설정을 저장합니다)" -- Needs review
-- LO["(Saves your current configuration, or restores a saved one.)"] = ""
LO["Scale"] = "크기"
LO["Set the bar font"] = "바 글자 설정"
LO["Show Bars"] = "바 보기"
LO["Show bars for %s"] = "%s 을(를) 표시" -- Needs review
LO["Show Expired Notices"] = "기술이 종료되었을 때 경고표시" -- Needs review
-- LO["Show message when someone breaks %s early"] = ""
-- LO["Show message when %s procs"] = ""
-- LO["Show notice when spell expires"] = ""
-- LO["Show Proc"] = ""
-- LO["Shows/Hides the draggable anchor"] = ""
-- LO["Shows test bars"] = ""
LO["Show Warnings"] = "경고 보기"
-- LO["Show warning when spell is about to expire"] = ""
LO["Show Who Broke It"] = "메즈를 깨운 사람을 표시" -- Needs review
-- LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = ""
LO["Target Alpha"] = "대상 투명도"
LO["Target Anchor"] = "대상 앵커"
-- LO["Targeted"] = ""
LO["Test"] = "테스트"
LO["Texture"] = "텍스쳐"
-- LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = ""
-- LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = ""
LO["Toggle Anchor"] = "앵커 전환"
LO["Toggle Sounds"] = "소리 전환"
-- LO["Track %s"] = ""
-- LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = ""
LO["Warning Sound"] = "소리 경고"
LO["Warning Text"] = "문자 경고"
LO["Warning Time"] = "시간 경고"
LO["Warning Time for %s"] = "%s 시간 경고"
LO["Width"] = "폭"

return
end

local LO = AL3:NewLocale(addonName, "ruRU")
if LO then
LO["Alpha"] = "Полупрозрачность"
LO["Alpha applied to bar"] = "Полупрозрачность применена к полосе"
LO["Alpha applied to Non-Target bars"] = "Применена полупрозрачность на полосах других мобов"
LO["Alpha applied to Target bar"] = "Применена полупрозрачность на полосе цели"
LO["Anchor"] = "Якорь"
LO["Anchor Options"] = "Параметры якоря"
LO["Anchor used for %s bar"] = "Якорь, используемый для полосы %s"
LO["Anchor used when %s is on something NOT your target"] = "Якорь, используемый когда %s не на вашей цели"
LO["Anchor used when %s is on your target"] = "Якорь, используемый когда %s на вашей цели"
LO["Background Colour"] = "Цвет фона"
LO["Bar Colour"] = "Цвет полосы"
LO["Bar Options"] = "Параметры полосы"
LO["Bar Text"] = "Текст полосы"
LO["Buffs"] = "Бафы"
LO["Change background colour"] = "Изменить цвет фона"
LO["Change bar colour"] = "Изменить цвет полосы"
LO["Change the font size"] = "Изменить размер шрифта"
LO["Change the height of the bars"] = "Изменить высоту полос"
LO["Change the scale of the bars"] = "Изменить масштаб полос"
LO["Change the sound played when %s expires."] = "Изменить звук, проигрываемый при истечении времени действия %s."
LO["Change the sound played when %s procs."] = "Изменить звук, проигрываемый при срабатывании %s."
LO["Change the sound played when warning time is reached"] = "Изменить звук, проигрываемый во время предупреждения"
LO["Change the texture of the bars"] = "Изменить текстуру полос"
LO["Change the width of the bars"] = "Изменить ширину полос"
LO["Change which way the bars run"] = "Изменить направление полос"
LO["Classic Anchors"] = "Классические якоря"
LO["Enable/Disable sounds for %s"] = "Включить/выключить звук для %s"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "Введите сообщение для прока %s"
LO["Enter text to appear on %s bars."] = "Введите текст для полос %s."
LO["Enter warning to appear when %s expires."] = "Введите текст предупреждения при истечении времени действия %s."
LO["Enter warning to appear when %s will fade."] = "Введите текст предупреждения при исчезновении %s."
LO["Expired Sound"] = "Звук по истечению действия"
LO["Expired Text"] = "Текст по истечению действия"
LO["Fade bars when out of combat"] = "Убирать полосы, когда не в бою"
LO["Font"] = "Шрифт"
LO["Font Size"] = "Размер шрифта"
LO["Grow Up"] = "Новые сверху"
LO["Height"] = "Высоты"
LO["Hide OOC"] = "Скрывать, когда не в бою"
LO["If checked, bars will stack above the anchor, not below"] = "Если включено, полосы будут появляться сверху якоря, а не под ним"
LO["Left to Right"] = "Слева направо"
LO["Max Bars"] = "Максимальное количество полос"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "Максимальное количество полос, показываемых в любое время. 0 - показывать все полосы"
LO["Modern Anchors"] = "Современные якоря"
LO["My Target Only"] = "Только моя цель"
LO["None"] = "Никаких"
LO["Non-Target Alpha"] = "Не мои цели полупрозрачны"
LO["Non-Target Anchor"] = "Якорь не моих целей"
LO["Non-Targeted"] = "Не мой цели"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "(Один якорь: только для цели. Полосы для остальных мобов будут затемнены.)"
LO["Orientation"] = "Ориентация"
LO["Proc Sound"] = "Звуки прока"
LO["Proc Text"] = "Текст прока"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "Сбросить якоря"
LO["Reset bars to their default positions on the screen"] = "Сбросить полосы в их позиции по умолчанию"
LO["Restore Custom"] = "Восстановить пользовательские параметры"
LO["Restored 'Custom Anchors' Preset"] = "Восстановлены параметры \"Пользовательских якорей\"" -- Needs review
LO["(Restores your saved configuration.)"] = "(Восстановить сохраненную конфигурацию)"
LO["Right to Left"] = "Справа налево"
LO["Save Custom"] = "Сохранить пользовательские"
LO["Saved 'Custom Anchors' Preset"] = "Сохранено в настройке 'Пользовательские якоря'"
LO["(Saves your current configuration.)"] = "(Сохранить текущую конфигурацию)"
LO["(Saves your current configuration, or restores a saved one.)"] = "(Сохранить текущую конфигурацию или восстанавить сохраненную)"
LO["Scale"] = "Масштаб"
LO["Set the bar font"] = "Выберите шрифт полосы"
LO["Show Bars"] = "Показать полосы"
LO["Show bars for %s"] = "Показать полосы для %s"
LO["Show Expired Notices"] = "Показывать уведомления об истечении"
LO["Show message when someone breaks %s early"] = "Вывести сообщение, когда кто-то сбивает %s раньше времени"
LO["Show message when %s procs"] = "Вывести сообщение при проке %s"
LO["Show notice when spell expires"] = "Вывести сообщение по истечению действия заклинания"
LO["Show Proc"] = "Показывать проки"
LO["Shows/Hides the draggable anchor"] = "Показать/спрятать перемещаемый якорь"
LO["Shows test bars"] = "Показать тестовые полосы"
LO["Show Warnings"] = "Показывать предупреждения"
LO["Show warning when spell is about to expire"] = "Вывести предупреждение о том, что действие заклинания заканчивается"
LO["Show Who Broke It"] = "Показать сбившего ваше заклинание"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s будет заменен стаками заклинаний. $m будет заменен именем моба. Все остальное останется как есть"
LO["Target Alpha"] = "Полупрозрачность цели"
LO["Target Anchor"] = "Якорь цели"
LO["Targeted"] = "Цель"
LO["Test"] = "Тест"
LO["Texture"] = "Текстура"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "Данные настройки применяются только к якорям и полупрозрачности. Если вы хотите сохранить всю конфигурацию (цвет полос, звуки предупреждение и т.п.) используйте \"Профили\""
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "(Три якоря: Ваша цель, Ваши (де)бафы на других мобах и все остальное. Все полупрозрачные)"
LO["Toggle Anchor"] = "Переключить якорь"
LO["Toggle Sounds"] = "Переключить звуки"
LO["Track %s"] = "Отслеживать %s"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "(Два якоря: Ваша цель и ваши (де)бафы. Показывает только дебафы только на вашей цели.)"
LO["Warning Sound"] = "Звук предупреждения"
LO["Warning Text"] = "Текст предупреждения"
LO["Warning Time"] = "Время предупреждения"
LO["Warning Time for %s"] = "Время предупреждения для %s"
LO["Width"] = "Ширина"

return
end

local LO = AL3:NewLocale(addonName, "zhCN")
if LO then
LO["Alpha"] = "透明度"
LO["Alpha applied to bar"] = "计时条透明度"
LO["Alpha applied to Non-Target bars"] = "非目标条透明度"
LO["Alpha applied to Target bar"] = "目标条透明度"
LO["Anchor"] = "锚点"
LO["Anchor Options"] = "锚点选项"
LO["Anchor used for %s bar"] = "%s 计时条的锚点"
LO["Anchor used when %s is on something NOT your target"] = "当 %s 不在你目标上时的锚点"
LO["Anchor used when %s is on your target"] = "当 %s 在你的目标上时的锚点"
LO["Background Colour"] = "背景颜色"
LO["Bar Colour"] = "计时条颜色"
LO["Bar Options"] = "计时条选项"
LO["Bar Text"] = "计时条文本"
LO["Buffs"] = "增益效果"
LO["Change background colour"] = "改变背景颜色"
LO["Change bar colour"] = "改变计时条颜色"
LO["Change the font size"] = "改变字体大小"
LO["Change the height of the bars"] = "改变计时条的高度"
LO["Change the scale of the bars"] = "改变计时条的缩放"
LO["Change the sound played when %s expires."] = "改变当 %s 消失时的音效。"
LO["Change the sound played when %s procs."] = "改变当 %s 触发时的音效。"
LO["Change the sound played when warning time is reached"] = "改变当警告时间已到时的音效。"
LO["Change the texture of the bars"] = "改变计时条的材质"
LO["Change the width of the bars"] = "改变计时条的宽度"
LO["Change which way the bars run"] = "改变计时条增长的方向"
LO["Classic Anchors"] = "经典锚点设置"
LO["Enable/Disable sounds for %s"] = "启用/停用 %s 的音效"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "输入当 %s 触发时显示的信息"
LO["Enter text to appear on %s bars."] = "输入显示在 %s 条上的文字。"
LO["Enter warning to appear when %s expires."] = "输入当 %s 消失时显示的信息。"
LO["Enter warning to appear when %s will fade."] = "输入当 %s 即将消失时显示的警告。"
LO["Expired Sound"] = "消失时的音效"
LO["Expired Text"] = "消失时的信息"
LO["Fade bars when out of combat"] = "离开战斗时隐藏计时条"
LO["Font"] = "字体"
LO["Font Size"] = "字体尺寸"
LO["Grow Up"] = "向上增长"
LO["Height"] = "高度"
LO["Hide OOC"] = "离开战斗时隐藏"
LO["If checked, bars will stack above the anchor, not below"] = "如果勾选，计时条会堆叠在锚点上方"
LO["Left to Right"] = "从左到右"
LO["Max Bars"] = "最大计时条数"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "同时可显示的计时条最大数量。0代表无限制。"
LO["Modern Anchors"] = "现代锚点设置"
LO["My Target Only"] = "只有我的目标"
LO["None"] = "无"
LO["Non-Target Alpha"] = "非目标透明度"
LO["Non-Target Anchor"] = "非目标锚点"
LO["Non-Targeted"] = "非目标"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "（一个锚点：目标。非目标无效。）"
LO["Orientation"] = "方向"
LO["Proc Sound"] = "触发音效"
LO["Proc Text"] = "触发信息"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "重设锚点"
LO["Reset bars to their default positions on the screen"] = "重置计时条至它们的预设位置"
LO["Restore Custom"] = "恢复自定义"
LO["Restored 'Custom Anchors' Preset"] = "恢复“自定义锚点”设置"
LO["(Restores your saved configuration.)"] = "（恢复你已保存的设置。）"
LO["Right to Left"] = "从右至左"
LO["Save Custom"] = "储存自定义"
LO["Saved 'Custom Anchors' Preset"] = "储存“自定义锚点”设置"
LO["(Saves your current configuration.)"] = "（保存你当前的设置。）"
LO["(Saves your current configuration, or restores a saved one.)"] = "（保存你当前的设置，或者恢复已保存的设置。）"
LO["Scale"] = "缩放"
LO["Set the bar font"] = "设定计时条字体"
LO["Show Bars"] = "显示计时条"
LO["Show bars for %s"] = "显示 %s 的计时条"
LO["Show Expired Notices"] = "显示消失提醒"
LO["Show message when someone breaks %s early"] = "当某人太早打破 %s 时显示信息"
LO["Show message when %s procs"] = "当 %s 触发时显示信息"
LO["Show notice when spell expires"] = "当法术消失时显示提醒"
LO["Show Proc"] = "显示触发提醒"
LO["Shows/Hides the draggable anchor"] = "显示/隐藏可拖动的锚点"
LO["Shows test bars"] = "显示测试计时条"
LO["Show Warnings"] = "显示警告"
LO["Show warning when spell is about to expire"] = "当法术快要消失时显示警告"
LO["Show Who Broke It"] = "显示谁打破它"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s会被替换成法术堆叠数。$m会被替换成目标名称。所有其他东西都会保持原样。"
LO["Target Alpha"] = "目标透明度"
LO["Target Anchor"] = "目标锚点"
LO["Targeted"] = "目标"
LO["Test"] = "测试"
LO["Texture"] = "材质"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "这些设置仅储存了锚点位置与透明度。如果你想要储存整个设置（包含计时条颜色,警告音效等。）请使用配置文件功能。"
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "（三个锚点：目标，非目标，自身增益。所有的透明度都是1。）"
LO["Toggle Anchor"] = "开启锚点"
LO["Toggle Sounds"] = "开启音效"
LO["Track %s"] = "追踪 %s"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "（两个锚点: 目标，自身增益。只显示目标的减益。）"
LO["Warning Sound"] = "警告音效"
LO["Warning Text"] = "警告文字"
LO["Warning Time"] = "警告时间"
LO["Warning Time for %s"] = "%s 的警告时间"
LO["Width"] = "宽度"

return
end

local LO = AL3:NewLocale(addonName, "zhTW")
if LO then
LO["Alpha"] = "透明度"
LO["Alpha applied to bar"] = "條列透明度"
LO["Alpha applied to Non-Target bars"] = "非目標條透明度"
LO["Alpha applied to Target bar"] = "目標條透明度"
LO["Anchor"] = "錨點"
LO["Anchor Options"] = "錨點選項"
LO["Anchor used for %s bar"] = "錨點使用 %s 條列"
LO["Anchor used when %s is on something NOT your target"] = "當 %s 不在你目標上時的錨點"
LO["Anchor used when %s is on your target"] = "當 %s 在你的目標上時的錨點"
LO["Background Colour"] = "背景顏色"
LO["Bar Colour"] = "條列顏色"
LO["Bar Options"] = "條列選項"
LO["Bar Text"] = "條列文字"
LO["Buffs"] = "增益效果"
LO["Change background colour"] = "改變背景顏色"
LO["Change bar colour"] = "改變條列顏色"
LO["Change the font size"] = "改變字型尺寸"
LO["Change the height of the bars"] = "改變條列的高度"
LO["Change the scale of the bars"] = "改變條列的大小"
LO["Change the sound played when %s expires."] = "變更當 %s 過期時的音效."
LO["Change the sound played when %s procs."] = "變更當 %s 觸發時的音效."
LO["Change the sound played when warning time is reached"] = "變更當警告時間已到達時的音效"
LO["Change the texture of the bars"] = "改變條列的材質"
LO["Change the width of the bars"] = "改變條列的寬度"
LO["Change which way the bars run"] = "變更條列增長的方向"
LO["Classic Anchors"] = "經典錨點設置" -- Needs review
LO["Enable/Disable sounds for %s"] = "啟用/停用音效 %s"
-- LO["Enter message to appear when %s is ready."] = ""
LO["Enter message to appear when %s procs"] = "當 %s 觸發時顯示文字"
LO["Enter text to appear on %s bars."] = "輸入顯示在 %s 條上的文字"
LO["Enter warning to appear when %s expires."] = "當 %s 過期時顯示警告"
LO["Enter warning to appear when %s will fade."] = "當 %s 消失時顯示警告"
LO["Expired Sound"] = "過期音效"
LO["Expired Text"] = "過期的文字"
LO["Fade bars when out of combat"] = "脫離戰鬥時條列消失"
LO["Font"] = "字型"
LO["Font Size"] = "字型尺寸"
LO["Grow Up"] = "向上增長"
LO["Height"] = "高度"
LO["Hide OOC"] = "離開戰鬥時隱藏"
LO["If checked, bars will stack above the anchor, not below"] = "假如勾選, 施法條會堆疊在錨點上方"
LO["Left to Right"] = "從左到右"
LO["Max Bars"] = "最大條列數"
LO["Maximum number of bars to show at any one time. Set to 0 to show all bars."] = "同時可顯示的條列最大數量. 0代表無限制"
LO["Modern Anchors"] = "摩登錨點設置" -- Needs review
LO["My Target Only"] = "只有我的目標"
LO["None"] = "無"
LO["Non-Target Alpha"] = "非目標透明度"
LO["Non-Target Anchor"] = "非目標錨點"
LO["Non-Targeted"] = "非目標"
LO["(One anchor: Targeted. Bars of non-targeted mobs are dimmed.)"] = "(一個錨點: 選擇的目標.非選擇目標調會變暗)"
LO["Orientation"] = "定向"
LO["Proc Sound"] = "觸發音效"
LO["Proc Text"] = "進程文字"
-- LO["Ready Text"] = ""
LO["Reset Anchors"] = "重設錨點"
LO["Reset bars to their default positions on the screen"] = "重置條列至他們的預設位置"
LO["Restore Custom"] = "恢復自訂"
LO["Restored 'Custom Anchors' Preset"] = "回復 '自訂錨點\" 設置" -- Needs review
LO["(Restores your saved configuration.)"] = "(恢復你的保存置配置。)"
LO["Right to Left"] = "從右至左"
LO["Save Custom"] = "儲存自訂"
LO["Saved 'Custom Anchors' Preset"] = "儲存 '自訂錨點' 設置"
LO["(Saves your current configuration.)"] = "(儲存你的目前配置。)"
LO["(Saves your current configuration, or restores a saved one.)"] = "(儲存你自訂的設定,或者是回復你自訂的設定)"
LO["Scale"] = "縮放"
LO["Set the bar font"] = "設定條列字型"
LO["Show Bars"] = "顯示條列"
LO["Show bars for %s"] = "顯示條列 %s"
LO["Show Expired Notices"] = "顯示過期公告"
LO["Show message when someone breaks %s early"] = "當某人太早打破 %s 時顯示訊息"
LO["Show message when %s procs"] = "當 %s 觸發時顯示訊息"
LO["Show notice when spell expires"] = "當法術到期時顯示提醒"
LO["Show Proc"] = "顯示進程"
LO["Shows/Hides the draggable anchor"] = "顯示/隱藏可拖動的錨點"
LO["Shows test bars"] = "顯示測試條列"
LO["Show Warnings"] = "顯示警告"
LO["Show warning when spell is about to expire"] = "當法術快要過期時顯示警告"
LO["Show Who Broke It"] = "顯示誰打破它"
LO["$s will be replaced by the spell stack. $m will be replaced by the mob name. Everything else will remain as-is."] = "$s 會被替換成法術堆疊數. $m會被替換成模組名稱. 所有其他東西都會保持原樣"
LO["Target Alpha"] = "目標透明度"
LO["Target Anchor"] = "目標錨點"
LO["Targeted"] = "目標"
LO["Test"] = "測試"
LO["Texture"] = "材質"
LO["These presets only store anchor and alpha information. If you want to save an entire configuration (including bar colours, warning sounds, etc.) use the Profiles feature."] = "這些設定僅儲存了錨點位置與透明度. 如果你想要儲存整個設定黨 (包含計時條顏色,警告音效等) 請使用設定檔功能"
LO["(Three anchors: Targeted, Non-Targeted and Buffs. All alphas 1.0.)"] = "(三個錨點: 選擇的目標,未選擇目標,增益效果. 所有的透明度都是1)"
LO["Toggle Anchor"] = "開啟錨點"
LO["Toggle Sounds"] = "開啟音效"
LO["Track %s"] = "追蹤 %s"
LO["(Two anchors: Targeted and Buffs. Only show debuffs on my target.)"] = "(兩個錨點: 選擇的目標,增益效果 只顯示我選擇目標的減益)"
LO["Warning Sound"] = "警告音效"
LO["Warning Text"] = "警告文字"
LO["Warning Time"] = "警告時間"
LO["Warning Time for %s"] = "警告時間 %s"
LO["Width"] = "寬度"

return
end
