--[[
************************************************************************
itIT.lua
itIT localization strings for Ackis Recipe List
************************************************************************
File date: 2012-08-18T04:52:05Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.4.1
************************************************************************
Original translated by: Pettigrow
Currently maintained by:
http://www.wowace.com/addons/arl/localization/translators/

Please update http://www.wowace.com/addons/arl/localization/itIT/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/arl/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "itIT", false)

if not L then return end

L["Aaron Hollman"] = true -- Needs review
L["Aayndia Floralwind"] = true -- Needs review
L["Abigail Shiel"] = true -- Needs review
L["About"] = "Circa" -- Needs review
L["Abyssal Flamebringer"] = true -- Needs review
L["ACHIEVEMENT_DESC"] = "Le ricette ottenute tramite Imprese devono essere incluse nella scansione." -- Needs review
L["ACQUIRETOOLTIPPOSITION_DESC"] = "Cambia il luogo del tooltip contenente le informazioni d'acquisizione." -- Needs review
L["Acquisition"] = "acquisizione" -- Needs review
L["Adele Fielder"] = true -- Needs review
L["Adelene Sunlance"] = true -- Needs review
L["Aendel Windspear"] = true -- Needs review
L["Aged Dalaran Wizard"] = true -- Needs review
L["Ainderu Summerleaf"] = true -- Needs review
L["Ainethil"] = true -- Needs review
L["Akham"] = true -- Needs review
L["Alanna Raveneye"] = true -- Needs review
L["Alard Schmied"] = true -- Needs review
L["Alchemist Gribble"] = "Gribble" -- Needs review
L["Alchemist Mallory"] = " Mallory" -- Needs review
L["Alchemist Pestlezugg"] = "Alchimista Pestlezugg" -- Needs review
L["Aldraan"] = true -- Needs review
L["Alegorn"] = true -- Needs review
L["Aleinia"] = true -- Needs review
L["Alestos"] = true -- Needs review
L["ALL_FILTERED"] = "Anche se hai già scansionato questa professione, i tuoi filtri stanno al momento prevenendo ad alcune ricette di essere mostrate. Per favore cambia i tuoi filtri e prova di nuovo." -- Needs review
L["ALT_CLICK"] = "Fai Alt-Clic per aggiungere/rimuovere questa ricetta alla tua lista ignorati." -- Needs review
L["ALT_TRADESKILL_DESC"] = [=[Questo mostrerà una lista di alt che hanno avuto le competenze scansionate.
Cliccando sul nome dell'alt mostrerà la professione in chat.
Alt-Clic sul nome dell'alt cancellerà l'alt dalla lista.]=] -- Needs review
L["Alys Vol'tyr"] = true -- Needs review
L["Amal'thazad"] = true -- Needs review
L["Amy Davenport"] = true -- Needs review
L["Anchorite Ensham"] = " Curatore Ensham" -- Needs review
L["Anchorite Fateema"] = "Curatore Fateema" -- Needs review
L["Anchorite Paetheus"] = "Curatore Paetheus" -- Needs review
L["Anchorite Yazmina"] = "Curatore Yazmina" -- Needs review
L["Andrew Hilbert"] = true -- Needs review
L["Andrion Darkspinner"] = true -- Needs review
L["Anvilrage Captain"] = "Capitano Anvilrage" -- Needs review
L["Anvilrage Marshal"] = "Maresciallo Anvilrage" -- Needs review
L["Apothecary Antonivich"] = "Farmacista Antonivich" -- Needs review
L["Apothecary Bressa"] = "Farmacista Bressa" -- Needs review
L["Apothecary Wormwick"] = "Farmacista Wormwick" -- Needs review
L["Apprentice Darius"] = "Apprendista Darius" -- Needs review
L["AQ40_RANDOM_BOP"] = "Drop casuale da AQ40, Si vincola alla raccolta." -- Needs review
L["ARCH_DROP_ULD"] = "Questa ricetta è un drop casuale dal \"Vaso Canopo\" quando collezioni manufatti per Archeologia." -- Needs review
L["ARL_ALLEXCLUDED"] = "Anche se hai già scansionato questa professione, le tue esclusioni stanno al momento prevenendo ad alcune ricette di essere mostrate. Per favore cambia le tue esclusioni e prova di nuovo." -- Needs review
L["ARL_ALLKNOWN"] = "Conosci tutte le ricette per questa professione." -- Needs review
L["ARL_SEARCHFILTERED"] = "La tua ricerca non ha risultati." -- Needs review
L["AUTOLOAD_DB_DESC"] = "Carica automaticamente tutti i database delle ricette di ARL quando fai una scansione datamining." -- Needs review
L["AUTOSCANMAP_DESC"] = "Mostra automaticamente tutti i punti quando fai una scansione delle ricette." -- Needs review
L["AUTOSCAN_TRAINERS_DESC"] = "Attiva la scansione agli istruttori per comparare livelli di competenza e metodi di acquisizione ricette." -- Needs review
L["AUTOSCAN_VENDORS_DESC"] = "Attiva la scansione dei mercanti per comparare i livelli di competenza e i metodi d'acquisizione delle ricette." -- Needs review
L["BOA_DESC"] = "Le ricette che creano oggetti che Si vincolano all'account Battle.net devono essere incluse nella scansione." -- Needs review
L["BOE_DESC"] = "Le ricette che creano oggetti che Si vincolano all'equipaggiamento devono essere incluse nella scansione." -- Needs review
L["BOP_DESC"] = "Le ricette che creano oggetti che Si vincolano alla raccolta devono essere incluse nella scansione." -- Needs review
L["BRD_RANDOM_ROOM"] = "C'è una chance di trovarla in 5 stanze diverse ai Sotterranei di Roccianera, ma è uno spawn casuale e a volte non spawna affatto." -- Needs review
L["BT_RANDOM"] = "Drop casuale dai mob/boss del Tempio Nero." -- Needs review
L["CLASS_DESC"] = "Includi questa classe nella scansione. Questo filtrerà su due fattori: 1) La classe può usare la ricetta e 2) la classe può imparare la ricetta." -- Needs review
L["CLEAR_EXCLUSION_LIST_DESC"] = "Rimuove tutte le ricette dalla lista d'esclusione." -- Needs review
L["CLEAR_WAYPOINTS_DESC"] = "Rimuove tutti i punti di ARL da TomTom." -- Needs review
L["CLOSE_DESC"] = "Chiudi la Finestra della Lista Ricette." -- Needs review
L["CLOSEGUI_DESC"] = "Chiudi la finestra di ARL quando la finestra di creazione è chiusa." -- Needs review
L["COMMAND_LINE_SCAN"] = "Per eseguire una scansione da riga di comando devi specificare la professione, come /arl scan incantamento" -- Needs review
L["COMMON_ISSUES_DESC"] = [=[Per favore fai riferimento a questi problemi comuni prima d'inviare una segnalazione bug.
1) La ricetta X non appare! - Controlla le tue impostazioni dei filtri per assicurarti la ricetta non sia filtrata.
2) A Runografia mancano così tanti glifi! Perché non sono elencati? - Disattiva il filtro 'classi'. Come predefinito (e per richiesta popolare) ARL mostra solo le ricette che la tua classe può usare e la maggior parte dei glifi non sono usabili dalla tua classe.
3) Non voglio vedere le ricette della fazione opposta! - Attiva il filtro fazioni. Questo imposterà per mostrare solo le ricette ottenibili dalla tua fazione. Se qualcosa appare ancora e non dovrebbe, per favore invia una segnalazione bug.]=] -- Needs review
L["COMPARE_TRAINER_ACQUIRE_DESC"] = "Compara i metodi d'acquisizione istruttori selezionati con quelli nel database di ARL." -- Needs review
L["CONTRACTALL_DESC"] = "Rimpicciolisci tutte le ricette sotto elencate." -- Needs review
L["CRAFTED_ENGINEERS"] = "La ricetta è creata dagli Ingegneri." -- Needs review
L["CTRL_CLICK"] = "Fai Ctrl-Clic per aggiungere il link di questa ricetta alla tua chat." -- Needs review
L["CTRL_SHIFT_CLICK"] = "Fai Ctrl-Maiusc-Clic per aggiungere l'oggetto alla mappa e mini-mappa." -- Needs review
L["Dagger"] = "Pugnale" -- Needs review
L["DAILY_COOKING_DAL"] = "Ottenuta casualmente completando una delle missioni giornaliere di cucina a Dalaran." -- Needs review
L["DAILY_COOKING_FISH"] = "Scegli Barile di Pesce quando completi una di queste missioni." -- Needs review
L["DAILY_COOKING_MEAT"] = "Scegli Cassa di Carne quando completi una di queste missioni." -- Needs review
L["DAILY_FISHING_SHATT"] = "Ottenuta casualmente completando una delle missioni giornaliere di pesca di Burning Crusade." -- Needs review
L["DATAMINE_OPTIONS_DESC"] = "Ti permette di personalizzare il datamining in-gioco di ARL." -- Needs review
L["DATAMINER_NODB_ERROR"] = "Database delle ricette non caricato. Per favore scansiona prima la professione e poi prova il datamining." -- Needs review
L["DATAMINER_SKILLLEVEL_ERROR"] = "Può essere usato solo per un istruttore di professione. Per favore apri l'istruttore e prova di nuovo." -- Needs review
L["DATAMINER_TRAINER_INFO"] = [=[Nome istruttore: %s
ID istruttore: %s]=] -- Needs review
L["DATAMINER_TRAINER_NOTTARGETTED"] = "Devi bersagliare l'istruttore quando esegui questo comando." -- Needs review
L["DATAMINER_VENDOR_INFO"] = [=[Nome mercante: %s
ID mercante: %s]=] -- Needs review
L["DATAMINER_VENDOR_NOTTARGETTED"] = "Devi bersagliare il mercante quando esegui questo comando." -- Needs review
L["DATAMINE_WARNING_DESC"] = "Per favore nota che abilitare Carica Automaticamente Database Ricette aumenterà la quantità di memoria usata da ARL. Abilitare Scansione Automatica Istruttori può causare un po' di lag quando l'istruttore è aperto. Questo sarà più evidente durante la prima scansione di un istruttore." -- Needs review
L["DEFAULT_RECIPE"] = "Imparata automaticamente quando impari la professione." -- Needs review
L["Discovery"] = "Scoperta" -- Needs review
L["DISCOVERY_ALCH_BC_XMUTE"] = "Scoperta facendo trasmutazioni di Primordiali." -- Needs review
L["DISCOVERY_ALCH_ELIXIRFLASK"] = "Scoperta facendo elisir o tonici usando ingredienti di Burning Crusade o superiori." -- Needs review
L["DISCOVERY_ALCH_NORTHREND_RESEARCH"] = "Ottenuta casualmente conducendo la ricerca alchemica di Nordania." -- Needs review
L["DISCOVERY_ALCH_NORTHREND_XMUTE"] = "Scoperta facendo trasmutazioni di Eterni." -- Needs review
L["DISCOVERY_ALCH_POTION"] = "Scoperta facendo pozioni usando ingredienti di Burning Crusade o superiori." -- Needs review
L["DISCOVERY_ALCH_PROT"] = "Scoperta creando Pozioni Maggiori della Difesa usando materiali di Burning Crusade." -- Needs review
L["DISCOVERY_DESC"] = "Le ricette ottenute tramite Scoperta devono essere incluse nella scansione." -- Needs review
L["DISCOVERY_INSC_BOOK"] = "Scoperta casualmente leggendo il Libro della Maestria dei Glifi." -- Needs review
L["DISCOVERY_INSC_MINOR"] = "Ottenuta casualmente conducendo la Ricerca Runografica Minore." -- Needs review
L["DISCOVERY_INSC_NORTHREND"] = "Ottenuta casualmente conducendo la Ricerca Runografica di Nordania." -- Needs review
L["DISPLAY_EXCLUSION_DESC"] = "Mostra le ricette che sono nella lista d'esclusione." -- Needs review
L["DISPLAY_OPTIONS_DESC"] = "Ti permette di personalizzare come si comporta la GUI." -- Needs review
L["DM_TRIBUTE"] = "Cassa della Tribute Run a Maglio Infausto" -- Needs review
L["DRAGONSOUL_RANDOM"] = "Drop casuale dai mob/boss di Anima del Drago." -- Needs review
L["ENG_DISC"] = "Questa è scoperta casualmente creando altri oggetti di Ingegneria." -- Needs review
L["ENG_FLOOR_ITEM_BRD"] = "Lo schema può essere trovato sul pavimento vicino Argelmach il Signore dei Golem ai Sotterranei di Roccianera. Solo gli ingegneri con competenza 300 possono imparare lo schema dopo averci cliccato sopra." -- Needs review
L["ENG_GNOMER"] = "Drop dai mob a Gnomeregan." -- Needs review
L["EXCLUDECOUNT_DESC"] = "Includi le ricette escluse nel conto delle ricette totali." -- Needs review
L["EXCLUSION_ISSUES_DESC"] = "Per aggiungere una ricetta nella lista d'esclusione (ignora), fai alt-clic su essa dalla finestra della ricetta. Per riavere la ricetta, apri le opzioni di ARL e attiva l'opzione \"Mostra Ricette Escluse\". Questo mostrerà tutte le ricette che hai escluso dalla tua scansione dalla tua prossima scansione. Quando l'hai fatto, fai di nuovo alt-clic sulla ricetta  per rimuoverla dalla lista d'esclusione." -- Needs review
L["EXPANDALL_DESC"] = [=[Espandi tutte le ricette sotto elencate.
Premi il tasto Maiusc per espandere le sotto-voci.]=] -- Needs review
L["EXPANSION_DESC_FORMAT"] = "Mostra le ricette introdotte in %s." -- Needs review
L["EXPANSION_FILTER_FORMAT"] = "Mostra una selezione di %s reputazioni da includere nella scansione." -- Needs review
L["FACTION_DESC_FORMAT"] = "Includi le ricette che devono prima essere ottenute dai giocatori %s." -- Needs review
L["FILTER_CLOSE_DESC"] = "Chiudi il pannello delle opzioni di filtro." -- Needs review
L["FILTERCOUNT_DESC"] = "Includi le ricette filtrate nel conto delle ricette totali." -- Needs review
L["FILTER_DESC_FORMAT"] = "Mostra le ricette di %s." -- Needs review
L["FILTERING_BINDING_DESC"] = "Configurazione per quali tipi di vincoli sono incluse nella scansione." -- Needs review
L["FILTERING_GENERAL_DESC"] = "Configurazione per diversi più tipi di filtri generali." -- Needs review
L["FILTERING_ITEM_DESC"] = "Configurazione per quali tipi d'oggetto sono inclusi nella scansione." -- Needs review
L["FILTERING_MISC_DESC"] = "Configurazione per opzioni varie che sono anche presenti nelle opzioni di visualizzazione." -- Needs review
L["FILTERING_OBTAIN_DESC"] = "Configurazione per quali metodi d'ottenimento delle ricette sono inclusi nella scansione." -- Needs review
L["FILTERING_PLAYERTYPE_DESC"] = "Configurazione per oggetti corrispondenti quali tipi di giocatore sono inclusi nella scansione." -- Needs review
L["FILTERING_QUALITY_DESC"] = "Configurazione per quali qualità di ricette devono essere incluse nella scansione." -- Needs review
L["FILTERING_REP_DESC"] = "Configurazione per quali ricette ricompense di reputazione sono incluse nella scansione." -- Needs review
L["FILTER_OPEN_DESC"] = "Apri il pannello delle opzioni di filtro." -- Needs review
L["FIRELANDS_RANDOM"] = "Drop casuale dai mob/boss delle Terre del Fuoco." -- Needs review
L["FONT_SIZE_DESC"] = "Cambia la dimensione dei font per ARL." -- Needs review
L["GAME_COMMANDS_DESC"] = [=[Riga di Comando:
Premi /arl per aprire la GUI. I comandi accettati includono:
- /arl about
  Apre la finestra d'informazioni, mostrando informazioni sulla mod.
- /arl sort o /arl sorting
  Apre le opzioni d'elenco.
- /arl documentation
  Apre la documentazione in-gioco riguardo ARL.
- /arl display
  Apre le opzioni di visualizzazione.
- /arl profile
  Apre le opzioni di profilo.
- /arl filter
  Apre le opzioni di filtraggio.
- /arl scan
  Effettua una scansione per le ricette mancanti. Questo è per le volte in cui non riesci ad accedere al pulsante scansione.
- /arl tradelinks
  Stampa una lista di tutti i link alle abilità della professione.

Cliccando:
Ackis Recipe List si comporterà diversamente in base a quali tasti di modifica usi per cliccare.

Pulsante Scansione:
Queste sono le funzionalità che si verificano quando premi sul pulsante scansione.

- Clic Normale
  Esegue una scansione della professione attuale mostrando le ricette in una nuova finestra.
- Clic Maiusc
  Genera un text dump della corrente professione in un formato (CSV, XML, BBC) specificato dall'utente.
- Clic Alt
  Rimuove tutti i punti sulla Mappa del Mondo e la Mini-mappa generati da ARL.
- Clic Ctrl
  Fornisce un codice di sviluppo da usare quando aggiorni istruttori, mercanti, ecc nel database ricette.

Ricette:
Queste sono le funzionalità che si verificano quando premi su una ricetta.

- Clic Normale
  Espande o riduce le informazioni d'acquisizione di una ricetta.
- Clic Maiusc
  Genera un link oggetto dell'oggetto che la ricetta creerà nella tua finestra chat predefinita.
- Clic Ctrl
  Genera un link incantesimo per la ricetta che hai cliccato.
- Clic Alt
  Aggiunge o rimuove una ricetta dalla lista d'esclusione.
- Clic Ctrl-Maiusc
  Aggiunge i metodi d'acquisizione della specifica ricetta nella Mappa del Mondo e Mini-mappa.]=] -- Needs review
L["Gems"] = "Gemme" -- Needs review
L["GENERATE_LINKS_DESC"] = "Genera link completi della professione." -- Needs review
L["GREEN_GEM"] = "Verde" -- Needs review
L["GROUP_TOGGLE_FORMAT"] = "Clic-Sinistro per selezionare o Clic-Destro per deselezionare tutti i filtri %s." -- Needs review
L["HENRY_STERN_RFD"] = "Ottenuta parlando con Henry Stern ai Sotterranei di Lamaspina." -- Needs review
L["HIDEPOPUP_DESC"] = "Previene i pop-up dal notificarti il perché la finestra di scansione è vuota. I pop-up saranno sempre visualizzati la prima volta dopo che una nuova versione è stata aggiunta." -- Needs review
L["HYJAL_RANDOM"] = "Drop casuale dai mob/boss della Sommità di Hyjal." -- Needs review
L["Imindril Spearsong"] = true -- Needs review
L["INSTANCE_DESC"] = "Le ricette ottenute dalle spedizioni (5 giocatori) devono essere incluse nella scansione." -- Needs review
L["KNOWN_DESC"] = "Includi tutte le ricette conosciute nella scansione." -- Needs review
L["LEATHER_DESC"] = "Le ricette che creano oggetti in cuoio devono essere incluse nella scansione." -- Needs review
L["LIMITED_SUPPLY"] = "Venduta in quantità limitata." -- Needs review
L["LORE_NORTH"] = "Puoi imparare questa ricetta se hai ottenuto l'impresa \"Storico di Nordania\"." -- Needs review
L["Main Filter Options"] = "Principali Opzioni di filtro"
L["MAINFILTER_OPTIONS_DESC"] = "Ti consente di specificare come ARL gestisce vari filtri."
L["MAIN_OPTIONS_DESC"] = "Opzioni principali di configurazione" -- Needs review
L["MAP_ISSUES_DESC"] = "ARL si basa su TomTom per aggiungere icone e punti alla Mappa del Mondo e alla Mini-mappa. Puoi personalizzarli andando nel menù di configurazione di ARl e scorrendo alle opzioni di visualizzazione. Se non hai TomTom installato, niente sarà aggiunto. Aggiungere icone automaticamente è disabilitato come predefinito." -- Needs review
L["MAP_OPTIONS_DESC"] = "Ti consente di cambiare come ARL si integra nella mappa del mondo e nella mini-mappa."
L["MC_RANDOM"] = "Drop casuale dai boss del Nucleo Ardente." -- Needs review
L["MISSING_LIBRARY"] = "%s è mancante. L'addon non può essere eseguito." -- Needs review
L["MOB_DROP_DESC"] = "Le ricette che sono Mob Drops devono essere incluse nella scansione." -- Needs review
L["NO_DISPLAY"] = "Non ci sono ricette da mostrare. Se visualizzi questo messaggio per favore invia un ticket su http://www.wowace.com/addons/arl/tickets elencando che filtri hai, qual è la tua lista esclusioni, quale professione e il numero di ricette conosciute/non conosciute." -- Needs review
L["NORTH_DUNG"] = "Puoi imparare questa ricetta se hai ottenuto l'impresa \"Eroe delle spedizioni di Nordania\"." -- Needs review
L["NOT_YET_SCANNED"] = "Non ancora scansionato!" -- Needs review
L["Obtain"] = "Ottenere" -- Needs review
L["Obtained From"] = "Ottenuto da" -- Needs review
L["Ockil"] = true -- Needs review
L["Ogg'marr"] = true -- Needs review
L["Oglethorpe Obnoticus"] = true -- Needs review
L["OGRI_DRAGONS"] = "Drop dagli elite ad Ogri'la." -- Needs review
L["Oil"] = "Olio" -- Needs review
L["Okothos Ironrager"] = true -- Needs review
L["Okuno"] = true -- Needs review
L["Olisarra the Kind"] = "Olisarra Kind" -- Needs review
L["Oluros"] = true -- Needs review
L["One-Handed Axe"] = "Ascia ad una mano" -- Needs review
L["One-Handed Mace"] = "Mazza ad una mano" -- Needs review
L["One-Handed Sword"] = "Spada ad una mano" -- Needs review
L["Onodo"] = true -- Needs review
L["Onslaught Mason"] = true -- Needs review
L["Ontuvo"] = true -- Needs review
L["ONYXIA_HEAD_QUEST"] = "La missione per ottenere la ricetta si apre dopo aver consegnato la Testa di Onyxia." -- Needs review
L["OpenTradeSkillWindow"] = [=[Apri la finestra di Abilità Commercio 
]=] -- Needs review
L["Opuno Ironhorn"] = true -- Needs review
L["ORANGE_GEM"] = "Arancione" -- Needs review
L["Orland Schaeffer"] = true -- Needs review
L["Orn Tenderhoof"] = true -- Needs review
L["Other Realms"] = "Altri reami" -- Needs review
L["Otho Moji'ko"] = true -- Needs review
L["Ounhulo"] = true -- Needs review
L["Outfitter Eric"] = true -- Needs review
L["PRISMATIC_GEM"] = "Prismatica" -- Needs review
L["PURPLE_GEM"] = "Viola" -- Needs review
L["PVP_DESC"] = "Le ricette ottenute tramite PVP devono essere incluse nella scansione." -- Needs review
L["QUALITY_GENERAL_DESC"] = "Includi oggetti di qualità %s nella scansione." -- Needs review
L["Quest"] = "Missione"
L["QUEST_DESC"] = "Le ricette ottenute come ricompense dalle missioni devono essere incluse nella scansione." -- Needs review
L["RAID_DESC"] = "Le ricette ottenute nelle incursioni (es: Nucleo Ardente, Caverna di Sacrespire, ecc.) devono essere incluse nella scansione." -- Needs review
L["RECIPE_BOA_DESC"] = "Le ricette che Si vincolano all'account Battle.net devono essere incluse nella scansione." -- Needs review
L["RECIPE_BOE_DESC"] = "Le ricette che Si vincolano all'equipaggiamento devono essere incluse nella scansione." -- Needs review
L["RECIPE_BOP_DESC"] = "Le ricette che Si vincolano alla raccolta devono essere incluse nella scansione." -- Needs review
L["RECIPE_EXCLUDED"] = "Ricette nella lista Esclusioni." -- Needs review
L["REMOVED_FROM_GAME"] = "Questa ricetta è stata rimossa dal gioco, ma può essere ancora ottenuta se qualcuno ha l'oggetto della ricetta." -- Needs review
L["REPORTING_BUGS_DESC"] = [=[Quando segnali un bug, per favore fai le seguenti cose:
1) Scarica la versione più recente, disponibile su http://www.wowace.com/addons/arl/files/
2) Assicurati che non ci sia già una segnalazione bug riguardante il tuo problema. Puoi controllare da http://www.wowace.com/addons/arl/tickets/
3) Disattiva addon come Skillet o ATSW.
4) Leggi la documentazione sulla segnalazione bug su http://www.wowace.com/addons/arl/pages/feedback-and-bug-reporting/
5) Se il tuo problema non è elencato e stai usando la versione più recente, controlla le tue impostazioni degli addon. Controlla filtri, profili, ecc.
6) Hai trovato un bug che nessuno ha segnalato prima. Crea un nuovo ticket su http://www.wowace.com/addons/arl/tickets/ con un inizio descrittivo riguardante il problema. Nel ticket assicurati d'includere il messaggio d'errore che hai ricevuto (solo il messaggio d'errore, non ho bisogno della lista degli addon che usi), la ricetta/professione con cui stavi lavorando e ogni altra informazione che pensi potrebbe aiutare.
Quando invii una segnalazione bug, NON includere tutti gli addon da swatter. Lo rende semplicemente difficile da leggere. Se vuoi una buona mod per segnalare errori, usa BugSack. Non inviare errori/ricette mancanti nei commenti, o mandarmeli via MP. Inviali come ticket così posso occuparmene e tracciarli facilmente.]=] -- Needs review
L["REPUTATION_DESC"] = "Le ricette ottenute tramite mercanti di reputazione devono essere incluse nella scansione." -- Needs review
L["RESET_DESC"] = "Reimposta Tutti i Filtri ai valori predefiniti." -- Needs review
L["RESET_WINDOW_DESC"] = "Reimposta la GUI di ARL alla posizione predefinita." -- Needs review
L["RETIRED_DESC"] = "Includi le ricette che non possono più essere ottenute." -- Needs review
L["ROLE_DESC_FORMAT"] = "Mostra le ricette preferite dalle classi %s." -- Needs review
L["SCANBUTTONPOSITION_DESC"] = "Ti permette di personalizzare dove è posizionato il bottone di scansione sulla finestra della professione." -- Needs review
L["SCAN_ENTIRE_DB_DESC"] = "Carica l'intero database ricette, e scansiona ogni singolo tooltip di ricette controllando le flag. Questo rallenterà il tuo computer e userà un sacco di memoria." -- Needs review
L["SCAN_PROF_DB_DESC"] = "Scansiona una professione specifica (nome minuscolo o id incantesimo) nel database ricette, scansionando i tooltip e comprandoli con il database interno." -- Needs review
L["SCAN_RECIPES_DESC"] = [=[Scansiona una professione aperta per le ricette mancanti.
Maiusc-clic per generare un text-dump.
Alt-clic per rimuovere tutti i punti dalla mini-mappa e la mappa del mondo.]=] -- Needs review
L["SCAN_SPELL_ID_DESC"] = "Scansiona un specifico ID incantesimo, scansionando il suo tooltip e comprandolo con il database interno." -- Needs review
L["SCAN_VENDOR_DESC"] = "Scansiona l'attuale mercante aperto per ricette e compara le informazioni con il database interno." -- Needs review
L["SCHOLO_BOOK_SPAWN"] = "Dopo che uccidi Jandice Barov a Scholomance, spawna un libro che ti fa imparare questa ricetta." -- Needs review
L["SEASONAL_DESC"] = "Le ricette ottenute in eventi mondiali devono essere incluse nella scansione." -- Needs review
L["SHIFT_CLICK"] = "Fai Maiusc-Clic per aggiungere il link all'item creato da questa ricetta alla tua chat." -- Needs review
L["SKILL_DESC"] = "Includi tutte le ricette nella scansione, ignorando il tuo attuale livello di competenza." -- Needs review
L["SKILL_TOGGLE_DESC"] = "Mostra le ricette in base al loro livello competenza invece che al loro nome." -- Needs review
L["SMALL_FONT_DESC"] = "Attiva per usare un font più piccolo per le voci nella lista ricette." -- Needs review
L["SORTING_DESC"] = "Cambia il modo in cui sono elencate le ricette mostrate." -- Needs review
L["Sorting Options"] = "Opzioni di ordinamento"
L["SORTING_OPTIONS_DESC"] = "Ti consente di personalizzare il modo in cui le ricette sono elencate."
L["SPECIALTY_DESC"] = "Includi le ricette per le professioni abbandonate." -- Needs review
L["SPECIFIC_REP_DESC"] = "Includi la fazione %s." -- Needs review
L["SPELLTOOLTIPPOSITION_DESC"] = "Cambia il luogo del tooltip contenente le informazioni delle ricette." -- Needs review
L["SSC_RANDOM"] = "Drop casuale dai mob di Caverna di Sacrespire." -- Needs review
L["STRATH_BS_PLANS"] = "I progetti di Forgiatura si trovano sul pavimento a Stratholme." -- Needs review
L["SUNWELL_RANDOM"] = "Drop casuale dai mob della Cittadella del Pozzo Solare." -- Needs review
L["TEXT_DUMP_DESC"] = "Cambia il modo in cui appare il text dump." -- Needs review
L["Text Dump Options"] = "Opzioni Text Dump" -- Needs review
L["TEXTDUMP_OPTIONS_DESC"] = "Opzioni per cambiare il comportamento del text dump." -- Needs review
L["TK_RANDOM"] = "Drop casuale da Forte Tempesta." -- Needs review
L["TOC25_RANDOM"] = "Drop casuale dall'Ordalia dei Crociati, versione normale da 25 giocatori." -- Needs review
L["Tooltip (Acquire) Position"] = "Posizione Tooltip (Acquisisci)" -- Needs review
L["TOOLTIP_HINT"] = "Nascondi Suggerimenti" -- Needs review
L["TOOLTIP_HINT_DESC"] = "Nasconde i suggerimenti in fondo al tooltip." -- Needs review
L["TOOLTIP_OPTIONS_DESC"] = "Ti consente di specificare come si comportano i tooltip per ARL. Il tooltip d'acquisizione elenca le varie informazioni su come ottenere la ricetta, mentre il tooltip dell'incantesimo elenca le informazioni della ricetta stessa."
L["Tooltip (Recipe) Position"] = "Posizione del Tooltip (Ricetta)" -- Needs review
L["TOOLTIP_SCALE_DESC"] = "Cambia la dimensione del tooltip di ARL. Varia da .5 a 1.5 (.9 è predefinito)" -- Needs review
L["Top"] = "In Alto" -- Needs review
L["Top Left"] = "In Alto a Sinistra" -- Needs review
L["Top Right"] = "In Alto a Destra" -- Needs review
L["Trainer"] = "Istruttore" -- Needs review
L["TRAINER_DESC"] = "Le ricette imparate dagli istruttori devono essere incluse nella scansione." -- Needs review
L["Transmute"] = "Trasmutazione" -- Needs review
L["Trinket"] = "Monile" -- Needs review
L["Two-Handed Axe"] = "Ascia a Due mani" -- Needs review
L["Two-Handed Mace"] = "Mazza a Due mani" -- Needs review
L["Two-Handed Sword"] = "Spada a Due mani" -- Needs review
L["UI_SCALE_DESC"] = "Cambia la dimensione dell'IU. Varia da .5 a 1.5 (1 è predefinito)" -- Needs review
L["ULDUAR_RANDOM"] = "Drop casuale dai boss di Ulduar." -- Needs review
L["UNIT_MAX_TOOLTIPS_DESC"] = "Numero massimo ricette da mostrare nei tooltip." -- Needs review
L["UNIT_TOOLTIPS_DESC"] = "Imposta se mostrare o no le ricette non conosciute nei tooltip dei mercanti, istruttori o mob che le portano." -- Needs review
L["UNKNOWN_DESC"] = "Includi tutte le ricette sconosciute nella scansione." -- Needs review
L["USING_FILTERS_DESC"] = [=[I filtri possono essere attivati o disattivati. Ci sono due tipi di filtri: uno che previene la ricetta di apparire del tutto, e uno che previene un tipo specifico d'informazione d'acquisizione dall'apparire.
Con il primo tipo di filtro, questi corrispondono alle proprietà della ricetta (es: vincolo). Se imposti ARL per non mostrare le ricette che Si vincolano alla raccolta, nessuna ricetta che Si vincola alla raccolta apparirà nella scansione. Il secondo tipo di filtro ha a che fare con le informazioni d'acquisizione. Se una ricetta è disponibile come mob drop, o da un mercante e tu imposti di non mostrare le ricette dei mercanti, la ricetta apparirà ancora ma le informazioni sul mercante saranno nascoste. La ragione è che c'è un altro modo per acquisire la ricetta (mob drop) così deve essere ancora inclusa nella scansione.
Per favore nota che i tooltip nasconderanno sempre i metodi d'acquisizione dell'altra fazione di una ricetta. Questo è stato fatto per risparmiare spazio nel tooltip, visto che possono diventare parecchio larghi.]=] -- Needs review
L["VENDOR_DESC"] = "Le ricette comprate dai mercanti devono essere incluse nella scansione." -- Needs review
L["VIEW_EXCLUSION_LIST_DESC"] = "Stampa una lista di tutte le ricette nella lista d'esclusione." -- Needs review
L["WAYPOINT_MAP_FORMAT"] = "Crea punti per le ricette mancanti su %s." -- Needs review
L["WAYPOINT_TOGGLE_FORMAT"] = "Crea punti per le ricette %s." -- Needs review
L["WORLD_DROP_DESC"] = "Le ricette che sono World Drop devono essere incluse nella scansione." -- Needs review
L["ToC/Description"] = "Ackis Recipe List è un addon che scansiona le tue competenze nelle professioni e fornisce informazioni su come ottenere ricette. Funziona per tutte le professioni, inclusa Forgiarune." -- Needs review
