--[[
************************************************************************
ptBR.lua
ptBR localization strings for Ackis Recipe List
************************************************************************
File date: 2011-09-04T15:07:34Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.3.0
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/arl/localization/translators/

Please update http://www.wowace.com/addons/arl/localization/ptBR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/arl/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "ptBR", false)

if not L then return end

L["Aaron Hollman"] = true -- Needs review
L["Aayndia Floralwind"] = true -- Needs review
L["Abigail Shiel"] = true -- Needs review
L["About"] = "Sobre"
L["Abyssal Flamebringer"] = true -- Needs review
L["ACHIEVEMENT_DESC"] = "Receitas obtidas por Conquistas serão incluídas neste escaneamento." -- Needs review
L["ACQUIRETOOLTIPPOSITION_DESC"] = "Muda a localização da dica contendo a informação adquirida." -- Needs review
L["Acquisition"] = "Aquisição"
L["Adele Fielder"] = true -- Needs review
L["Adelene Sunlance"] = true -- Needs review
L["Aelthin"] = true -- Needs review
L["Aendel Windspear"] = true -- Needs review
L["Aged Dalaran Wizard"] = "Mago Idoso de Dalaran" -- Needs review
L["Ainderu Summerleaf"] = true -- Needs review
L["Ainethil"] = true -- Needs review
L["Akham"] = true -- Needs review
L["Alanna Raveneye"] = true -- Needs review
L["Alard Schmied"] = true -- Needs review
L["Alchemist Gribble"] = "Alquimista Gribble" -- Needs review
L["Alchemist Mallory"] = "Alquimista Mallory" -- Needs review
L["Alchemist Pestlezugg"] = "Alquimista Pestlezugg" -- Needs review
L["Aldraan"] = true -- Needs review
L["Alegorn"] = true -- Needs review
L["Aleinia"] = true -- Needs review
L["Alestos"] = true -- Needs review
L["Alestus"] = true -- Needs review
L["Alexandra Bolero"] = true -- Needs review
L["Alexandra McQueen"] = true -- Needs review
L["Alexis Marlowe"] = true -- Needs review
L["Algernon"] = "\009Algernon" -- Needs review
L["ALL_FILTERED"] = "Apesar de você já ter escaneado esta profissão, seus filtros estão atualmente impedindo que quaisquer receitas sejam exibidas. Por favor, altere seus filtros e tente novamente."
L["Allison"] = true -- Needs review
L["Almaador"] = true -- Needs review
L["Altaa"] = true -- Needs review
L["ALT_CLICK"] = "Alt-Clique para adicionar/remover esta receita de sua lista de ignoradas."
L["Alurmi"] = true -- Needs review
L["Alys Vol'tyr"] = true -- Needs review
L["Amal'thazad"] = true -- Needs review
L["Amy Davenport"] = true -- Needs review
L["Anchorite Ensham"] = "Anacoreta Ensham" -- Needs review
L["Anchorite Fateema"] = "Anacoreta Fateema" -- Needs review
L["Anchorite Paetheus"] = "Anacoreta Paetheus" -- Needs review
L["Anchorite Yazmina"] = "Anacoreta Yazmina" -- Needs review
L["Andellion"] = true -- Needs review
L["Andrew Hilbert"] = true -- Needs review
L["Andrion Darkspinner"] = true -- Needs review
L["Androd Fadran"] = true -- Needs review
L["Anger Guard"] = "Guarda Raivoso" -- Needs review
L["Annora"] = true -- Needs review
L["Anuur"] = true -- Needs review
L["Anvilrage Captain"] = "Capitão Anvilrage" -- Needs review
L["Anvilrage Marshal"] = true -- Needs review
L["Apothecary Antonivich"] = "Boticário Antonivich" -- Needs review
L["Apothecary Bressa"] = "Boticário Bressa" -- Needs review
L["Apothecary Wormwick"] = "Boticário Wormwick" -- Needs review
L["Apprentice Darius"] = "Aprendiz Darius" -- Needs review
L["Arathel Sunforge"] = true -- Needs review
L["Arcanist Sheynathren"] = true -- Needs review
L["Arcatraz Sentinel"] = true -- Needs review
L["ARCH_DROP_ULD"] = "Esta receita é um prêmio aleatório de um \"Jar Canopic\" durante a coleta de artefatos de Arqueologia." -- Needs review
L["Archmage Alvareaux"] = true -- Needs review
L["Aresella"] = true -- Needs review
L["Argent Quartermaster Hasana"] = "Contramestre Argêntea Hasana" -- Needs review
L["Argent Quartermaster Lightspark"] = "Contramestre Argêntea Lightspark" -- Needs review
L["Argo Strongstout"] = true -- Needs review
L["Arkkoran Oracle"] = "Arkkoran Oráculo" -- Needs review
L["ARL_ALLEXCLUDED"] = "Embora você já tenha escaneado esta profissão, suas exclusões estão atualmente impedindo que quaisquer receitas sejam exibidas. Por favor, altere suas exclusões e tente novamente."
L["ARL_ALLKNOWN"] = "Você conhece todas as receitas desta profissão."
L["ARL_SEARCHFILTERED"] = "Sua pesquisa não teve resultados" -- Needs review
L["Arras"] = true -- Needs review
L["Arred"] = true -- Needs review
L["Arrond"] = true -- Needs review
L["Arthur Henslowe"] = true -- Needs review
L["Arthur Moore"] = true -- Needs review
L["Artificer Daelo"] = "Artífice Daelo" -- Needs review
L["Asarnan"] = true -- Needs review
L["Ashtongue Warrior"] = "Ashtongue Guerreiro" -- Needs review
L["Aska Mistrunner"] = true -- Needs review
L["Auchenai Monk"] = "Monge Auchenai" -- Needs review
L["AUTOLOAD_DB_DESC"] = "Automaticamente carrega todas as receitas do ARL do banco de dados quando fazer um escaneamento \"datamining\"." -- Needs review
L["Auto Load Recipe Database"] = "Auto Carregar Banco de Dados de Receitas" -- Needs review
L["Auto Scan Map"] = "Auto Escanear Mapa" -- Needs review
L["AUTOSCANMAP_DESC"] = "Mostra automaticamente todos \"waypoints\" quando fizer um escaneamento de receita." -- Needs review
L["Auto Scan Trainers"] = "Auto Escanear Treinadores" -- Needs review
L["AUTOSCAN_TRAINERS_DESC"] = "Ativa o escaneamento em treinadores para comparar niveis de habilidades, e métodos de aquisição de receitas." -- Needs review
L["Auto Scan Vendors"] = "Auto Escanear Vendedores" -- Needs review
L["AUTOSCAN_VENDORS_DESC"] = "Ativa o escaneamento em vendedores para comparar níveis de habilidade, e métodos de aquisição de receitas." -- Needs review
L["Awan Iceborn"] = true -- Needs review
L["Awilo Lon'gomba"] = true -- Needs review
L["Banalash"] = true -- Needs review
L["Barien"] = true -- Needs review
L["Barim Spilthoof"] = true -- Needs review
L["Bash'ir Spell-Thief"] = true -- Needs review
L["Baxter"] = true -- Needs review
L["BBCode"] = true -- Needs review
L["BC_WOW_DESC"] = "Receitas disponíveis  com The Burning Crusade." -- Needs review
L["Belil"] = true -- Needs review
L["Bemarrin"] = true -- Needs review
L["Binding"] = "Vinculando" -- Needs review
L["BOA_DESC"] = "Receitas que criem itens que vinculam-se à Conta serão incluídas no escaneamento." -- Needs review
L["BOAFilter"] = "Item vinculado à Conta" -- Needs review
L["BOE_DESC"] = "Receitas que criem itens que Vinculam-se ao Equipar serão incluídas no escaneamento." -- Needs review
L["BOEFilter"] = "Item Vinculado ao Equipar" -- Needs review
L["BOP_DESC"] = "Receitas que criem itens que Vinculam-se ao Pegar serão incluídas no escaneamento." -- Needs review
L["BOPFilter"] = "Item Vinculado ao Pegar" -- Needs review
L["Borto"] = true -- Needs review
L["Borya"] = true -- Needs review
L["Bottom"] = "Inferior" -- Needs review
L["Bottom Left"] = "Botão Esquerdo" -- Needs review
L["Bottom Right"] = "Inferior à direita" -- Needs review
L["Bow"] = "Arco" -- Needs review
L["Bro'kin"] = true -- Needs review
L["BT_RANDOM"] = "Saque aleatório dos \"trash\"/Chefes do Templo Negro." -- Needs review
L["BUGGED"] = "ESTA RECEITA ESTÁ CORRENTEMENTE \"BUGADA\" NA ÚLTIMA VERSÃO ATIVA." -- Needs review
L["Captured Gnome"] = "Gnomo Capturado" -- Needs review
L["CATA_WOW_DESC"] = "Receitas disponíveis com Cataclysm." -- Needs review
L["Cielstrasza"] = true -- Needs review
L["CLASS_DESC"] = "Inclui esta classe no escaneamento. Isto filtrará em dois fatores: 1) Se a classe pode usar esta receita e 2) Se a classe pode aprender esta receita"
L["Classes"] = true
L["Clear Exclusion List"] = "Limpar Lista de Exclusão"
L["CLEAR_EXCLUSION_LIST_DESC"] = "Remove todas as receitas da lista de exclusão." -- Needs review
L["Clear Waypoints"] = "Limpar \"Waypoints\"" -- Needs review
L["CLEAR_WAYPOINTS_DESC"] = "Remove todos \"waypoints\" do ARL do TomTom" -- Needs review
L["Cloak"] = "Capa"
L["CLOSE_DESC"] = "Fechar a janela da Lista de Receitas."
L["Close GUI"] = "Fechar com Tradeskill UI" -- Needs review
L["CLOSEGUI_DESC"] = "Fechar a janela ARL quando a janela da profissão for fechada."
L["Cloth"] = "Pano" -- Needs review
L["COMMAND_LINE_SCAN"] = "Para executar um escaneamento por uma linha de comando você precisa especificar uma profissão como: /arl scan encantamento" -- Needs review
L["Common Issues"] = "Problemas comuns"
L["COMMON_ISSUES_DESC"] = [=[Por favor, verifique estes problemas comuns antes de submeter um relatório de erro
1) Receita X não aparece! - Verifique suas configurações de filtro para certificar-se de que a receita não foi filtrada.
2) Faltam vários glifos para Escrivão! Por quê não estão na lista?  Desabilite seu filtro de "classes". Por padrão (e devido a pedidos populares) ARL somente mostrará receitas que a sua classe pode usar e a maioria dos glifos não são utilizáveis pela sua classe.
3) Eu não quero ver as receitas da facção oposta! Ligue o filtro de facção. Isto fará com que a lista tenha somente receitas adquiríveis pela sua facção. Se ainda aparecer algo que não deveria, por favor encaminhe um relatório de erros.]=] -- Needs review
L["Compare Trainer Acquire"] = "Comparar Aquisição do Treinador" -- Needs review
L["COMPARE_TRAINER_ACQUIRE_DESC"] = "Compara os metodos de aquisição do treinador selecionado com os que estão no banco de dados do ARL." -- Needs review
L["CONTRACTALL_DESC"] = "Minimizar todas as receitas listadas abaixo" -- Needs review
L["\"Cookie\" McWeaksauce"] = "\"Biscoito\" McMolhofraco" -- Needs review
L["Coreiel"] = true -- Needs review
L["CRAFTED_ENGINEERS"] = "Receita é criada por Engenheiros." -- Needs review
L["Crossbow"] = "Besta" -- Needs review
L["CTRL_CLICK"] = "Ctrl-Clique para adicionar o link desta receita ao bate-papo." -- Needs review
L["CTRL_SHIFT_CLICK"] = "Ctrl-Shift-Click para adicionar o item ao mapa e mini-mapa." -- Needs review
L["Dagger"] = "Adaga"
L["DAILY_COOKING_DAL"] = "Aleatoriamente obtidas completando qualquer missão diária de culinária de Dalaran." -- Needs review
L["DAILY_FISHING_SHATT"] = "Obtido aleatoriamente completando qualquer missão diária de pesca do BC." -- Needs review
L["DATAMINER_TRAINER_NOTTARGETTED"] = "Você deve dar alvo ao treinador quando usar este comando." -- Needs review
L["DATAMINER_VENDOR_INFO"] = [=[Nome do Vendedor: %s
ID do Vendedor: %s]=] -- Needs review
L["Defias Enchanter"] = "Encantador Defias" -- Needs review
L["Defias Pirate"] = "Pirata Defias" -- Needs review
L["Defias Renegade Mage"] = "Defias O Mago Renegado" -- Needs review
L["DISPLAY_EXCLUSION_DESC"] = "Mostrar receitas que estão na lista de exclusão." -- Needs review
L["Eclipsion Cavalier"] = true -- Needs review
L["Eiin"] = true -- Needs review
L["ENG_DISC"] = "Isto é descoberto aleatoriamente enquanto cria-se outros itens de Engenharia." -- Needs review
L["ENG_GNOMER"] = "Pego de monstros em Gnomeregan." -- Needs review
L["Erilia"] = true -- Needs review
L["EXCLUDECOUNT_DESC"] = "Incluir receitas excluídas na contagem de receitas totais." -- Needs review
L["Exclusion Issues"] = "Questões de Exclusão" -- Needs review
L["EXCLUSION_ISSUES_DESC"] = "Para adicionar uma receita para a lista de exclusão(ignorados), apenas alt-clique nela pela janela de receitas. Para ter esta receita de volta, abra as opções do ARL e deixe a opção \"Mostrar Receitas Excluídas\" ativada. Isto irá mostrar todas as receitas que você excluiu no seu escaneamento durante o seu próximo escaneamento. Depois que tiver feito isto, Alt Clique na receita novamente para remove-la da lista de exclusão." -- Needs review
L["EXPANDALL_DESC"] = [=[Expandir todas as receitas listadas abaixo.
Pressione a tecla Shift para expandir sub-entradas.]=] -- Needs review
L["FACTION_DESC_FORMAT"] = "Inclui receitas que precisam primeiro ser obtidas por %s jogadores." -- Needs review
L["Farii"] = true -- Needs review
L["Fazu"] = true -- Needs review
L["Feera"] = true -- Needs review
L["Felannia"] = true -- Needs review
L["Festive Recipes"] = "Receitas Festivas" -- Needs review
L["FILTER_CLOSE_DESC"] = "Fecha o painel de opções de filtro." -- Needs review
L["FILTERCOUNT_DESC"] = "Inclui receitas filtradas na contagem de receitas totais." -- Needs review
L["FILTERING_BC_DESC"] = "Configuração para quais receitas recompensadas pela Reputação do Burning Crusade estão incluídos na verificação." -- Needs review
L["FILTERING_BINDING_DESC"] = "Configuração para quais tipos de vinculamentos serão incluídos no escaneamento." -- Needs review
L["FILTERING_CATA_DESC"] = "Configuração para quais receitas premiadas pela Reputação do Cataclysm serão inlcuídas no escaneamento." -- Needs review
L["FILTERING_GENERAL_DESC"] = "Configurações para outras vários tipos de filtros gerais." -- Needs review
L["FILTERING_ITEM_DESC"] = "Configurações para quais tipos de itens serão incluídos no escaneamento." -- Needs review
L["FILTERING_MISC_DESC"] = "Configurações para opções variadas aos quais tambem estão presentes nas opções de visualização." -- Needs review
L["FILTERING_OBTAIN_DESC"] = "Configuração para quais métodos para obtenção de receitas são inlcuídos no escaneamento." -- Needs review
L["FILTERING_PLAYERTYPE_DESC"] = "Configurações para itens comparados pelo o que o jogador digita são incluídas neste escaneamento." -- Needs review
L["FILTERING_QUALITY_DESC"] = "Configurações para quais tipos de qualidade da receita será incluída no escaneamento." -- Needs review
L["FILTER_OPEN_DESC"] = "Abre o painel de opções de filtro." -- Needs review
L["FIRELANDS_RANDOM"] = "Saque aleatório dos chefes/trash das Terras de Fogo." -- Needs review
L["Fizzix Blastbolt"] = true -- Needs review
L["Fono"] = true -- Needs review
L["FONT_SIZE_DESC"] = "Muda o tamanho das fontes do ARL." -- Needs review
L["Game Commands"] = "Comandos de Jogo" -- Needs review
L["Gara Skullcrush"] = "Gara Esmagador de Crânios" -- Needs review
L["Gearcutter Cogspinner"] = true -- Needs review
L["Geba'li"] = true -- Needs review
L["Geen"] = true -- Needs review
L["Gelanthis"] = true -- Needs review
L["General Options"] = "Opções Gerais" -- Needs review
L["GENERATE_LINKS_DESC"] = "Gerará links completos de profissões." -- Needs review
L["Gharash"] = true -- Needs review
L["Ghok'kah"] = true -- Needs review
L["Godan"] = true -- Needs review
L["Goli Krumn"] = true -- Needs review
L["Gonto"] = true -- Needs review
L["Greatfather Winter"] = "Papai Inverno" -- Needs review
L["Great-father Winter's Helper"] = "Ajudante do Papai Inverno" -- Needs review
L["Grikka"] = true -- Needs review
L["Grimtak"] = true -- Needs review
L["Grutah"] = true -- Needs review
L["Gun"] = "Arma de Fogo" -- Needs review
L["Haalrun"] = true -- Needs review
L["Haferet"] = true -- Needs review
L["Hagrus"] = true -- Needs review
L["Hama"] = true -- Needs review
L["Hamanar"] = true -- Needs review
L["Hide Pop-Up"] = "Ocultar Pop-Up" -- Needs review
L["HIDEPOPUP_DESC"] = "Previni que pop-ups notifiquem você o porque a janela de escaneamento está vazia. Pop-ups sempre aparecerão pela primeira vez depois que uma nova versão for adicionada." -- Needs review
L["Imindril Spearsong"] = true -- Needs review
L["Inessera"] = true -- Needs review
L["INSTANCE_DESC"] = "Receitas obtidas em (5 homens) Instancias serão incluídas neste scaneamento." -- Needs review
L["Item"] = true -- Needs review
L["Jaquilina Dramet"] = true -- Needs review
L["Kalaen"] = true -- Needs review
L["Kalinda"] = true -- Needs review
L["Kanaria"] = true -- Needs review
L["Kania"] = true -- Needs review
L["Krek Cragcrush"] = true -- Needs review
L["Krugosh"] = true -- Needs review
L["Krunn"] = true -- Needs review
L["Landraelanis"] = true -- Needs review
L["Lardan"] = true -- Needs review
L["Leather"] = "Couro" -- Needs review
L["LEATHER_DESC"] = "Receitas que criam itens de couro serão incluídas no escaneamento." -- Needs review
L["Left"] = "Esquerda" -- Needs review
L["LIMITED_SUPPLY"] = "Vendido em quantidade limitada." -- Needs review
L["LK_WOW_DESC"] = "Receitas disponiveis com Wrath of the Lich King." -- Needs review
L["Location"] = "Local" -- Needs review
L["Logannas"] = true -- Needs review
L["Magar"] = true -- Needs review
L["Mahani"] = true -- Needs review
L["Mahu"] = true -- Needs review
L["Mail"] = "Malha" -- Needs review
L["Main Filter Options"] = "Principais Opções de filtro."
L["MAINFILTER_OPTIONS_DESC"] = "Permite que você especifique como o ARL manipula filtros diferentes."
L["Main Options"] = "Opções principais" -- Needs review
L["MAIN_OPTIONS_DESC"] = "Configurações das opões principais" -- Needs review
L["Mak"] = true -- Needs review
L["Makaru"] = true -- Needs review
L["Map Issues"] = "questões do mapa" -- Needs review
L["MAP_ISSUES_DESC"] = "ARL depende de TomTom para adicionar ícones e \"waypoints\" para o Mapa-Mundi e o Mini-Mapa. Você pode customizar estes indo no menu de  configurações do ARL e navegar para opções de visualização. Se você não tem TomTom instalado, nada será adicionado. Auto adicionar ícones está desabilitado por padrão." -- Needs review
L["MAP_OPTIONS_DESC"] = "Permite-lhe alterar a forma como o ARL integra o mapa do mundo e no mini-mapa."
L["Martine Tramblay"] = true -- Needs review
L["MC_RANDOM"] = "Saque aleatório dos chefes do Núcleo Derretido." -- Needs review
L["Miall"] = true -- Needs review
L["Mining"] = "Mineração" -- Needs review
L["Miralisse"] = true -- Needs review
L["MissingFromDB"] = [=[": está faltando na base de dados.
Por favor informe ao autor do add-on sobre esta receita."]=] -- Needs review
L["MISSING_LIBRARY"] = "%s está faltando. O addon não pode executar." -- Needs review
L["Mob Drop"] = "Saque de monstro" -- Needs review
L["MOB_DROP_DESC"] = "Receitas que caem de Mobs deverão ser incluídos neste scan." -- Needs review
L["Muuran"] = true -- Needs review
L["Naka"] = true -- Needs review
L["Nakodu"] = true -- Needs review
L["NAXX40_GONE"] = "Removido do jogo quando Naxx 40 foi retirado." -- Needs review
L["Necklace"] = "Colar" -- Needs review
L["Nergal"] = true -- Needs review
L["Nioma"] = true -- Needs review
L["NO_DISPLAY"] = "Sem receitas pra mostrar. Se você recebeu está mensagem, por favor submita um \"ticket\" em http://www.wowace.com/addons/arl/tickets listando quais filtros você tem, qual sua lista de exclusão, quais profissões, e o numero de receitas conhecidas/desconhecidas." -- Needs review
L["NoItemLink"] = "Este item não possui um link ou não estava emseu cache." -- Needs review
L["NOTSCANNED"] = "Você não escaneou está profissão ainda. Por favor abra sua profissão e clique em Scan." -- Needs review
L["NOT_YET_SCANNED"] = "Ainda não escaneado." -- Needs review
L["Nurse Neela"] = "Enfermeira Neela" -- Needs review
L["Nus"] = true -- Needs review
L["Obtain"] = "Obter"
L["Obtained From"] = "Obtido de"
L["OGRI_DRAGONS"] = "Saque dos elites em Ogri'la" -- Needs review
L["Oil"] = "Oleo" -- Needs review
L["Oluros"] = true -- Needs review
L["One-Handed Axe"] = "Machado de Uma Mão" -- Needs review
L["One-Handed Mace"] = "Maça de Uma Mão" -- Needs review
L["One-Handed Sword"] = "Espada de Uma Mão" -- Needs review
L["Onodo"] = true -- Needs review
L["ONYXIA_HEAD_QUEST"] = "A missão para obter a receita aparece após a entrega da cabeça de Onyxia." -- Needs review
L["OpenTradeSkillWindow"] = "Por Favor abra a janela de profissão para escanear." -- Needs review
L["ORANGE_GEM"] = "Laranja" -- Needs review
L["ORIGINAL_WOW_DESC"] = "Receita disponivel com o jogo original." -- Needs review
L["Orland Schaeffer"] = true -- Needs review
L["Other Realms"] = "Outros Reinos." -- Needs review
L["Plate"] = true -- Needs review
L["Polearm"] = "Arma de Haste" -- Needs review
L["Potion"] = "Poção" -- Needs review
L["PRISMATIC_GEM"] = "Prismatica" -- Needs review
L["Profile"] = "Perfis" -- Needs review
L["Profile Options"] = "Opções do perfil"
L["Punra"] = true -- Needs review
L["PURPLE_GEM"] = "Roxa" -- Needs review
L["PVP_DESC"] = "Receitas obtidas por JxJ serão incluídas neste escaneamento." -- Needs review
L["QUALITY_GENERAL_DESC"] = "Inclui receitas de qualidade %s no escaneamento." -- Needs review
L["Quarelestra"] = true -- Needs review
L["Quelis"] = true -- Needs review
L["Quest"] = "Missão" -- Needs review
L["QUEST_DESC"] = "Receitas obtidas por missões serão inlcuída no escaneamento." -- Needs review
L["RAID_DESC"] = "Receitas obtidas em raides (pe: Núcleo Derretido, Caverna do Serpentário, etc) deverão ser incluídas neste scan." -- Needs review
L["Ranik"] = true -- Needs review
L["Rawrk"] = true -- Needs review
L["RECIPE_BOA_DESC"] = "Receitas que vinculam-se à conta deverão ser incluídas neste scan." -- Needs review
L["RecipeBOAFilter"] = "Receita Vinculada à Conta" -- Needs review
L["RECIPE_BOE_DESC"] = "Receitas que vinculam-se ao equipar deverão ser incluídas neste scan." -- Needs review
L["RecipeBOEFilter"] = "Receita Vinculada ao Equipar" -- Needs review
L["RECIPE_BOP_DESC"] = "Receitas que vinculam-se ao serem coletadas deverão ser incluídas neste scan" -- Needs review
L["RecipeBOPFilter"] = "Receita Vinculada ao Recolher" -- Needs review
L["RECIPE_EXCLUDED"] = "Receita na Lista de Exclusão" -- Needs review
L["Recipes In Tooltips"] = "Receitas nas Dicas" -- Needs review
L["Refik"] = true -- Needs review
L["REMOVED_FROM_GAME"] = "Esta receita foi removida do jogo, mas ainda pode ser obtivel se alguem ainda possui o item da receita." -- Needs review
L["Reporting Bugs"] = "Reportar \"Bugs\"" -- Needs review
L["REPORTING_BUGS_DESC"] = [=[Quando reportar um "Bug", por favor tenha certeza de fazer o seguinte:
1) Baixe a última versão, disponivel em http://www.wowace.com/addons/arl/files/
2) Tenha certeza que já não existe um relatório seu sobre este problema. Você pode verificar isso em http://www.wowace.com/addons/arl/tickets/
3) Disative addons como Skillet ou ATSW.
4) Leia a documentação de relatório de "bugs" em http://www.wowace.com/addons/arl/pages/feedback-and-bug-reporting/
5) Se o problema não estiver listado e você estiver usando a última versão verifique as configurações do seu adon. Verifique filtros, perfis, etc.
6) Você encontrou um "bug" que ninguem relatou antes. Crie um novo ticket em http://www.wowace.com/addons/arl/tickets/ com um título descritivo sobre o problema. No ticket tenha certeza qu você inclua a mensagem de erro que você recebeu (apenas a mensagem de erro, eu não preciso de uma listagem dos addons que você usa), a receita/profissão que você estava trabalhando, e qualquer outra informação que você acha que possa ajudar.
Quando postar um relatório de 
'bug, NÃO inclua todos os addons. Isto faz que fique dificil de ler. Se você quer um mod pra relatórios de erro, obtenha BugSack. Não poste receitas erros/perdidas nos comentários, ou enviar ele a mim por PM. Poste eles como um ticket ao qual eu posso endereçar e cuidar facilmente.]=] -- Needs review
L["Reset Window Position"] = "Resetar a Posição da Janela" -- Needs review
L["Retired"] = "Retirado" -- Needs review
L["RETIRED_DESC"] = "Incluei receitas que não podem mais ser adquiridos." -- Needs review
L["Ring"] = "Anel" -- Needs review
L["Rod"] = "Vara" -- Needs review
L["Rogvar"] = true -- Needs review
L["Rohok"] = true -- Needs review
L["ROLE_DESC_FORMAT"] = "Mostrar receitas favorecidas por %s classes" -- Needs review
L["Runda"] = true -- Needs review
L["Rungor"] = true -- Needs review
L["Sathein"] = true -- Needs review
L["Scan"] = "Escanear" -- Needs review
L["Scan Button Position"] = "Posição do Botão Escanear" -- Needs review
L["SCANBUTTONPOSITION_DESC"] = "Permite que você personalize onde o botão de digitalização é colocado no quadro tradeskill." -- Needs review
L["SCAN_RECIPES_DESC"] = [=[Escanea uma profissão aberta por receitas perdidas.
Shift-Clique par gerar um despejo de texto.
Alt-Clique para remover todos "waypoints" do mini-mapa e mapa mundi]=] -- Needs review
L["Scan Vendor"] = "Escanear Vendedor" -- Needs review
L["Scargil"] = true -- Needs review
L["Scarlet Archmage"] = "Arquimago Escarlate" -- Needs review
L["SCHOLO_BOOK_SPAWN"] = "Depois que você matar Jandice Barov em Scolomântia, um livro aparecerá e voce poderá aprender esta receita." -- Needs review
L["Shaani"] = true -- Needs review
L["Shield"] = "Escudo" -- Needs review
L["Sid Limbardi"] = true -- Needs review
L["SKILL_DESC"] = "Iclui todas as receitas no escaneamento, independente do nivel de sua abilidade." -- Needs review
L["Son of Arkkoroc"] = "Filho de Arkkoroc" -- Needs review
L["Sort"] = "Especificar." -- Needs review
L["Sorting Options"] = "Opções de Classificação" -- Needs review
L["SORTING_OPTIONS_DESC"] = "Permite personalizar a maneira como as receitas indicadas são classificadas." -- Needs review
L["Specialties"] = "Especialidades" -- Needs review
L["SPECIALTY_DESC"] = "incluem receitas para especializações não treinados." -- Needs review
L["SPECIFIC_REP_DESC"] = "Incluir facção %s" -- Needs review
L["Spectral Researcher"] = "Pesquisador espectral" -- Needs review
L["SpellIDCache"] = "Feitiço ID: %s não está no seu cache local. Por favor submeta um ticket em http://www.wowace.com/addons/arl/tickets/ e inclua o ID do feitiço e a profissão na qual você estava escaneando." -- Needs review
L["Staff"] = "Cajado" -- Needs review
L["Sunfury Arcanist"] = true -- Needs review
L["Tamar"] = true -- Needs review
L["Tanaika"] = true -- Needs review
L["Tanak"] = true -- Needs review
L["Tari'qa"] = true -- Needs review
L["Tatiana"] = true -- Needs review
L["Teg Dawnstrider"] = true -- Needs review
L["Telonis"] = true -- Needs review
L["Tepa"] = true -- Needs review
L["Text Dump"] = "Despejo de Texto" -- Needs review
L["TEXT_DUMP_DESC"] = "Muda como o despejo de texto aparece." -- Needs review
L["Text Dump Options"] = "Opções do Despejo de Texto" -- Needs review
L["TEXTDUMP_OPTIONS_DESC"] = "Opções para mudar o comportamento do despejo de texto." -- Needs review
L["Thomas Kolichio"] = true -- Needs review
L["Thrown"] = "Arremesso" -- Needs review
L["Thuzadin Shadowcaster"] = true -- Needs review
L["Tomas"] = true -- Needs review
L["Tooltip (Acquire) Position"] = "Posição da Dica (Aquisição)" -- Needs review
L["TOOLTIP_HINT"] = "Ocultar Texto de Segestão" -- Needs review
L["TOOLTIP_HINT_DESC"] = "Oculta o texto de sugestão no fundo da dica." -- Needs review
L["Tooltip Options"] = "Opções da Dica" -- Needs review
L["TOOLTIP_OPTIONS_DESC"] = "Permite-lhe especificar como a dica para o ARL irá se comportar. A dica de aquisição lista as diferentes informações sobre como adquirir a receita, enquanto que o feitiço da dica lista as informações da própria receita." -- Needs review
L["Tooltip (Recipe) Position"] = "Posição da Dica (Receita)" -- Needs review
L["Tooltip Scale"] = "Escala da Dica" -- Needs review
L["TOOLTIP_SCALE_DESC"] = "Muda a escala das dicas do ARL. Variam de .5 a 1.5(.9 é o padrão)" -- Needs review
L["Top"] = "Superior" -- Needs review
L["Top Left"] = "Superior à esquerda" -- Needs review
L["Top Right"] = "Superior à direita" -- Needs review
L["Trainer"] = "Treinador" -- Needs review
L["TRAINER_DESC"] = "Receitas aprendidas por treinadores serão incluídas neste escaneamento." -- Needs review
L["Transmute"] = "Transmutar" -- Needs review
L["Trinket"] = "Berloque" -- Needs review
L["Tunkk"] = true -- Needs review
L["Two-Handed Axe"] = "Machado de Duas Mãos" -- Needs review
L["Two-Handed Mace"] = "Maça de Duas Mãos" -- Needs review
L["Two-Handed Sword"] = "Espada de Duas Mãos" -- Needs review
L["UI_SCALE_DESC"] = "Muda a escala da IU. Varia entre .5 a 1.5 (1 é o padrão)" -- Needs review
L["ULDUAR_RANDOM"] = "Saque aleatório dos chefes de Ulduar." -- Needs review
L["Una"] = true -- Needs review
L["UNIT_MAX_TOOLTIPS_DESC"] = "Numero máximo de receitas mostradas nas dicas." -- Needs review
L["UNIT_TOOLTIPS_DESC"] = "Muda quando deve-se ou não mostrar receitas desconhecidas nas dicas de vendedores, treinadores, ou monstros que os carregam." -- Needs review
L["UNKNOWN_DESC"] = "Incluir todas as receitas desconhecidas no escaneamento."
L["Uriku"] = true -- Needs review
L["Using Filters"] = "Usando Filtros" -- Needs review
L["USING_FILTERS_DESC"] = [=[Filtros podem ser Ativados ou desativados. Existem três tipos de filtros: um ao qual previne que receitas apareçam mesmo, e um ao qual vai prevenir um tipo especifico de informação de aquisição de aparecer.
Com o tipo de filtro, este comparará as propriedades da receita (pe: vinculamento). Se você por o ARL para não mostrar receitas VaR, nenhuma receita VaR irá aparecer no escaneamento. O segundo tipo de filtro cuida de informação de aquisição. Se uma receita está disponivel em saque de monstros, ou de um vendedor e você escolhe não mostrar receitas de vendedores, a receita irá aparecer mas a informação do vendedor será ocultada. O motivo é que existe outro meio de adquirir a receita (saque de monstro) então ela ainda será incluída no escaneamento.
Por favor note que as dicas sempre irão ocultar os metodos de aquisição da facção oposta. Isto foi feito para salvar espaço nas dicas já que elas podem ficar bem grandes.]=] -- Needs review
L["Vaean"] = true -- Needs review
L["Vargus"] = true -- Needs review
L["Vendor"] = "Vendedor" -- Needs review
L["VENDOR_DESC"] = "Receitas compradas de vendedores serão incluídas neste escaneamento." -- Needs review
L["View Exclusion List"] = "Ver Lista de Exclusão" -- Needs review
L["VIEW_EXCLUSION_LIST_DESC"] = "Grava uma lista de todas as receitas na lista de exclusão." -- Needs review
L["Vivianna"] = "Viviana" -- Needs review
L["Waldor"] = true -- Needs review
L["Wand"] = "Varinha" -- Needs review
L["WAYPOINT_MAP_FORMAT"] = "Cria \"waypoints\" ára receitas perdidas em %s." -- Needs review
L["WAYPOINT_TOGGLE_FORMAT"] = "Cria \"Waypoints\" para %s receitas." -- Needs review
L["Weapon"] = "Arma" -- Needs review
L["Weapon Technician"] = "Técnico de Armas" -- Needs review
L["Wik'Tar"] = true -- Needs review
L["Winter Reveler"] = true -- Needs review
L["World Drop"] = "Saque Mundial" -- Needs review
L["WORLD_DROP_DESC"] = "Receitas que são Saques Mundiais serão incluídas neste scaneamento." -- Needs review
L["Wulan"] = true -- Needs review
L["Ythyar"] = true -- Needs review
L["Zurai"] = true -- Needs review
L["ToC/Title"] = "Ackis Recipe List" -- Needs review
